### ISSUE TITLE
Missing stashing workflow documentation

### ISSUE THREAD

**Issue by cbarrete** [arxanas/git-branchless#1012]
### Wiki page

https://github.com/arxanas/git-branchless/wiki/Workflow:-stashing

### Description

I'm interested in your workflow regarding stashing, as I still find myself using `git stash` sometimes.

By the way, thanks for `git-branchless` and for the great documentation!

**Comment by claytonrcarter** [comment]
FYI there has also been discussion of this at https://github.com/arxanas/git-branchless/discussions/979

**Comment by arxanas** [comment]
Unfortunately I never created the `--stash` flag as discussed in https://github.com/arxanas/git-branchless/discussions/979#discussioncomment-6334488, so the workflow itself is a little clumsy.

**Comment by cbarrete** [comment]
Got it, thanks! I somehow missed those discussions.
