### ISSUE TITLE
About 0.8.0 release

### ISSUE THREAD

**Issue by chenrui333** [arxanas/git-branchless#1048]
👋 it looks like 0.8.0 still did not get marked as latest release. Raise this issue for some awareness. Thanks!

relates to Homebrew/homebrew-core#140742

**Comment by arxanas** [comment]
I haven't had time to write the release notes yet, but will hopefully get around to it soon.

**Comment by chenrui333** [comment]
👍 thanks!

**Comment by arxanas** [comment]
Published https://github.com/arxanas/git-branchless/releases/tag/v0.8.0.
