### ISSUE TITLE
`git amend` in the middle of stack results in detached HEAD

### ISSUE THREAD

**Issue by pink** [arxanas/git-branchless#1059]
### Description of the bug

Prior to v0.8.0, if I used `git amend` in the middle of my stack it would result in the changes being amended and the branch still checked out. Now the changes are still amended, but I end up in a detached state. Is this expected?

### Version of `rustc`

rustc 1.65.0 (897e37553 2022-11-02)

### Version of `git-branchless`

git-branchless-opts 0.8.0

### Version of `git`

git version 2.39.2 (Apple Git-143)

**Comment by arxanas** [comment]
I haven't looked into this, but presumably the bugfix in https://github.com/arxanas/git-branchless/pull/876 is bad.
