### ISSUE TITLE
Git stash alternative docs?

### ISSUE THREAD

**Issue by cameronelliott** [arxanas/git-branchless#1151]
### Wiki page

https://github.com/arxanas/git-branchless/wiki/Workflow:-stashing

### Subcommand

not sure

### Description

The wiki page "Workflow:stashing" says to file an issue if we are curious about the git-branchless workflow alternative to using `git stash`
Well, I'll say I'm interested, in case you feel like filling in that page.
(Just getting started with 'branchless, and as I was going to stash something I knew there must be a 'branchless approach using a commit somehow rather than stashing stuff away)

**Comment by arxanas** [comment]
See https://github.com/arxanas/git-branchless/discussions/979#discussioncomment-6334488; we might also see stash support soon in https://github.com/arxanas/git-branchless/pull/1150!
