### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [arxanas/git-branchless#1284]
Please release a new version, the latest 0.8.0 is over 7 months old and uses outdated dependencies.

Depends on #1285

**Comment by chenrui333** [comment]
also relates to https://github.com/Homebrew/homebrew-core/pull/166983

**Comment by maxhaton** [comment]
I think a new release is also required to pick up the fix for hooks in powershell?

@arxanas ?

**Comment by arxanas** [comment]
Released in https://github.com/arxanas/git-branchless/releases/tag/v0.9.0.

**Comment by maxhaton** [comment]
> Released in https://github.com/arxanas/git-branchless/releases/tag/v0.9.0.

thanks
