### ISSUE TITLE
Smartlog displays uncolored output under `watch --color git sl`

### ISSUE THREAD

**Issue by bcongdon** [arxanas/git-branchless#130]
I'd expect `watch --color git sl` to output a colored output, but it seems to display the uncolored output.

Perhaps smartlog needs something like `--color=always` to override whatever detection mechanism it's using for whether to display colors

**Comment by arxanas** [comment]
Colors (and fancy glyphs — the two are currently inseparable) are detected here:

https://github.com/arxanas/git-branchless/blob/62bafe36b4e1a9f1d576e5a4505e72156bb468e4/src/commands.rs#L98

It might suffice to add a `--glyphs=[text|fancy]` parameter here:

https://github.com/arxanas/git-branchless/blob/62bafe36b4e1a9f1d576e5a4505e72156bb468e4/src/opts.rs#L228-L237

It would also be good to respect `$NO_COLOR`: https://no-color.org/
