### ISSUE TITLE
Could not parse reference-transaction-line

### ISSUE THREAD

**Issue by akheron** [arxanas/git-branchless#1388]
### Description of the bug

I've been getting these error messages for a while now on one repository. The error appears on basically every command, just pasting the output from `git sw` here:

```
$ git sw master
branchless: creating working copy snapshot
branchless: running command: git checkout master
2024-08-21T11:22:20.676532Z ERROR git_branchless_hook: Could not parse reference-transaction-line err=
   0: Could not parse OID from string
   1: Git error GenericError: unable to parse OID - contains invalid characters

Location:
   git-branchless-lib/src/git/repo.rs:289

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: git_branchless_hook::reference_transaction::parse_reference_transaction_line with line="0000000000000000000000000000000000000000 ref:refs/heads/master HEAD"
      at git-branchless-hook/src/lib.rs:289
   1: git_branchless_hook::hook_reference_transaction with effects=<Output fancy=false> transaction_state="committed"
      at git-branchless-hook/src/lib.rs:416
   2: git_branchless_hook::command_main with ctx=CommandContext { effects: <Output fancy=false>, git_run_info: <GitRunInfo path_to_git="git" working_directory="/Users/akheron/work/evaka" env=not shown> } args=HookArgs { subcommand: ReferenceTransaction { transaction_state: "committed" } }
      at git-branchless-hook/src/lib.rs:524

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets. line="0000000000000000000000000000000000000000 ref:refs/heads/master HEAD"
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
branchless: processing checkout
```

### Expected behavior

No error message

### Actual behavior

Error message gets printed, but everything seems to work anyway.

#### Software version

git-branchless 0.9.0

#### Operating system

macOS 14.6.1 (Darwin 23.6.0)

#### Command-line

```bash
/opt/homebrew/bin/git-branchless bug-report
```

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=vim
```

#### Git version

```
> git version
git version 2.46.0
```

#### Hooks

<details>
<summary>Show 7 hooks</summary>

##### Hook `post-applypatch`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-applypatch "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-checkout`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-checkout "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-commit`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-commit "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-merge`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-merge "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-rewrite`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-rewrite "$@"
## END BRANCHLESS CONFIG
```
##### Hook `pre-auto-gc`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook pre-auto-gc "$@"
## END BRANCHLESS CONFIG
```
##### Hook `reference-transaction`

```
#!/bin/sh
## START BRANCHLESS CONFIG

# Avoid canceling the reference transaction in the case that `branchless` fails
# for whatever reason.
git branchless hook reference-transaction "$@" || (
echo 'branchless: Failed to process reference transaction!'
echo 'branchless: Some events (e.g. branch updates) may have been lost.'
echo 'branchless: This is a bug. Please report it.'
)
## END BRANCHLESS CONFIG
```

</details>

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 35315, transaction ID: 33688 (message: checkout)

1. `WorkingCopySnapshot { timestamp: 1724239340.575745, event_tx_id: Id(33688), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(fbc061e3bfde92de3776485ffbc2b42fc28340b2), ref_name: Some(ReferenceName("refs/heads/redacted-ref-0")) }`
1. `RefUpdateEvent { timestamp: 1724239340.811952, event_tx_id: Id(33688), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: dccbc753b2efb11d4549de666785b0035454aba1, message: None }`
```
:
O 773160d 5d (redacted-ref-1) xxx xxxx xxxxx xx xxxxx xxxxxx xxxx
:
O 63c012d 5d (redacted-ref-2) xxx x xxxxxxx xxxxxxxxxxx xxxx
:
O f04467d 4d (redacted-ref-3) xxx xxx
:
O f3d9e38 1d (redacted-ref-4) xxxxxx xxxx xxxxxxx xxxxxxxxxxx xxx xxxxxxxx xxxxxxxx
:
@ dccbc75 2h (> master) xxxxxxxxxx xxxxxx xxxxx xxxxxxx
|\
| o a141bba 3m xxxxxxxx xxxxxxxx xxxxxx xxxxx
| |
| o 14ccb65 3m xxxxxx xxxx xxxxxxxxxxx xx xxxxxxxxxxxxx xx xxxxx
| |
| o 544a41d 3m (redacted-ref-0) xxxx xxxxxxxxxx xxxxxxxxxx xxxx xxxxxxxxxx
|\
| o 2445452 2m xxx
|\
| o 4931995 2m (redacted-ref-5) xxxxx xxxxxxxxxxxx xx xxxxxxxxx xxx xxxxxxx xxx xxxx
|\
| o 6573850 2m xxx xxxx xxxxx xxx xxxxxxx xxxxxx xxxxxx
|\
| o 71f2cb3 2m xxxxxxxxx xxxxx xxxxx xxxxxxxxxxxxxx
|\
| o b2b627a 2m (redacted-ref-6) xxxx xxxxxx xx xxxxxxxxxxxxxx
|\
| o b77c2b2 2m xxxxxxxxxxxx xxxxxx xxxx
|\
| o cb3d04e 2m xxxx xxxxx xxxxxxxxxxxxx
|
o dc15639 2m (redacted-ref-7) xxxxxxxxxxxx xxxxxxx xxx
```
##### Event ID: 35288, transaction ID: 33687 (message: sync)

1. `RewriteEvent { timestamp: 1724239250.808678, event_tx_id: Id(33687), old_commit_oid: 1a02dcd8b1f3f2efe832c15cccfac41c46004fd0, new_commit_oid: 71f2cb308de2178bcd6b644d19b3059ff6714206 }`
1. `WorkingCopySnapshot { timestamp: 1724239250.908397, event_tx_id: Id(33687), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(2639a6a4c0d5dab01d7dbeb3b76c599508f742c7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1724239251.107935, event_tx_id: Id(33687), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
1. `RefUpdateEvent { timestamp: 1724239251.197458, event_tx_id: Id(33687), ref_name: ReferenceName("refs/heads/redacted-ref-7"), old_oid: 39ce9ec5bb88e38e953e1b97a2bac17facc86a01, new_oid: dc156390a8c7a2cc1c10b2c79da1c4432454cb67, message: None }`
1. `RewriteEvent { timestamp: 1724239251.231169, event_tx_id: Id(33687), old_commit_oid: 39ce9ec5bb88e38e953e1b97a2bac17facc86a01, new_commit_oid: dc156390a8c7a2cc1c10b2c79da1c4432454cb67 }`
1. `WorkingCopySnapshot { timestamp: 1724239251.325049, event_tx_id: Id(33687), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(2639a6a4c0d5dab01d7dbeb3b76c599508f742c7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1724239251.541467, event_tx_id: Id(33687), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
1. `RewriteEvent { timestamp: 1724239251.628058, event_tx_id: Id(33687), old_commit_oid: 8af7125bb86b8b239f8550d94a28629225b2a2bc, new_commit_oid: cb3d04eb15e22370bc9d5298f20fca771be8a4ef }`
1. `WorkingCopySnapshot { timestamp: 1724239251.716164, event_tx_id: Id(33687), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(2639a6a4c0d5dab01d7dbeb3b76c599508f742c7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1724239251.924091, event_tx_id: Id(33687), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
1. `RefUpdateEvent { timestamp: 1724239251.975681, event_tx_id: Id(33687), ref_name: ReferenceName("refs/heads/redacted-ref-6"), old_oid: 9c64bde2ea4ade7f3eafc66d88685c9febda25ca, new_oid: b2b627a6b0ec1b63a62e87bca56b4deddf0f3dfd, message: None }`
1. `RewriteEvent { timestamp: 1724239252.009575, event_tx_id: Id(33687), old_commit_oid: 9c64bde2ea4ade7f3eafc66d88685c9febda25ca, new_commit_oid: b2b627a6b0ec1b63a62e87bca56b4deddf0f3dfd }`
1. `WorkingCopySnapshot { timestamp: 1724239252.09864, event_tx_id: Id(33687), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(2639a6a4c0d5dab01d7dbeb3b76c599508f742c7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1724239252.293237, event_tx_id: Id(33687), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
1. `RewriteEvent { timestamp: 1724239252.383702, event_tx_id: Id(33687), old_commit_oid: a2793e803ce4a59e10c220fa032f5f4b6ee5c013, new_commit_oid: b77c2b2f56b17ee5b1dfe813c72707320209d79c }`
1. `WorkingCopySnapshot { timestamp: 1724239252.477687, event_tx_id: Id(33687), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(2639a6a4c0d5dab01d7dbeb3b76c599508f742c7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1724239252.675708, event_tx_id: Id(33687), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
1. `RewriteEvent { timestamp: 1724239252.758248, event_tx_id: Id(33687), old_commit_oid: 64aae79f0e91fc33f2d4129710316f26d497f21d, new_commit_oid: 244545217eb3ad720d1f22baf423df659da4935e }`
1. `WorkingCopySnapshot { timestamp: 1724239252.846989, event_tx_id: Id(33687), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(2639a6a4c0d5dab01d7dbeb3b76c599508f742c7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1724239253.058517, event_tx_id: Id(33687), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
1. `RewriteEvent { timestamp: 1724239253.182744, event_tx_id: Id(33687), old_commit_oid: 339bd3cff909231028dea090923cf4bc839be084, new_commit_oid: 657385064f22f6f700db48cfac3dce4194f23da2 }`
1. `WorkingCopySnapshot { timestamp: 1724239253.270574, event_tx_id: Id(33687), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(2639a6a4c0d5dab01d7dbeb3b76c599508f742c7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1724239253.468381, event_tx_id: Id(33687), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
1. `RefUpdateEvent { timestamp: 1724239253.538763, event_tx_id: Id(33687), ref_name: ReferenceName("refs/heads/redacted-ref-5"), old_oid: 205c5e9ae13232fc0c600957fa6ff30625497787, new_oid: 49319958a2f84fca5987fb2a12cd7820781ac285, message: None }`
1. `RewriteEvent { timestamp: 1724239253.572564, event_tx_id: Id(33687), old_commit_oid: 205c5e9ae13232fc0c600957fa6ff30625497787, new_commit_oid: 49319958a2f84fca5987fb2a12cd7820781ac285 }`
1. `WorkingCopySnapshot { timestamp: 1724239253.66353, event_tx_id: Id(33687), head_oid: 544a41dce571419d530d0f96f61f698aeee424c3, commit_oid: NonZeroOid(2639a6a4c0d5dab01d7dbeb3b76c599508f742c7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1724239253.85967, event_tx_id: Id(33687), ref_name: ReferenceName("HEAD"), old_oid: 544a41dce571419d530d0f96f61f698aeee424c3, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
```
:
O 773160d 5d (redacted-ref-1) xxx xxxx xxxxx xx xxxxx xxxxxx xxxx
:
O 63c012d 5d (redacted-ref-2) xxx x xxxxxxx xxxxxxxxxxx xxxx
:
O f04467d 4d (redacted-ref-3) xxx xxx
:
O f3d9e38 1d (redacted-ref-4) xxxxxx xxxx xxxxxxx xxxxxxxxxxx xxx xxxxxxxx xxxxxxxx
:
@ dccbc75 2h (> master) xxxxxxxxxx xxxxxx xxxxx xxxxxxx
|\
| o a141bba 3m xxxxxxxx xxxxxxxx xxxxxx xxxxx
| |
| o 14ccb65 3m xxxxxx xxxx xxxxxxxxxxx xx xxxxxxxxxxxxx xx xxxxx
| |
| o 544a41d 3m (redacted-ref-0) xxxx xxxxxxxxxx xxxxxxxxxx xxxx xxxxxxxxxx
|\
| o 2445452 2m xxx
|\
| o 4931995 2m (redacted-ref-5) xxxxx xxxxxxxxxxxx xx xxxxxxxxx xxx xxxxxxx xxx xxxx
|\
| o 6573850 2m xxx xxxx xxxxx xxx xxxxxxx xxxxxx xxxxxx
|\
| o 71f2cb3 2m xxxxxxxxx xxxxx xxxxx xxxxxxxxxxxxxx
|\
| o b2b627a 2m (redacted-ref-6) xxxx xxxxxx xx xxxxxxxxxxxxxx
|\
| o b77c2b2 2m xxxxxxxxxxxx xxxxxx xxxx
|\
| o cb3d04e 2m xxxx xxxxx xxxxxxxxxxxxx
|
o dc15639 2m (redacted-ref-7) xxxxxxxxxxxx xxxxxxx xxx
```
##### Event ID: 35287, transaction ID: 33685 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1724239244.338445, event_tx_id: Id(33685), ref_name: ReferenceName("refs/remotes/redacted-ref-8"), old_oid: 0000000000000000000000000000000000000000, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
```
:
O 773160d 5d (redacted-ref-1) xxx xxxx xxxxx xx xxxxx xxxxxx xxxx
:
O 63c012d 5d (redacted-ref-2) xxx x xxxxxxx xxxxxxxxxxx xxxx
:
O f04467d 4d (redacted-ref-3) xxx xxx
:
O f3d9e38 1d (redacted-ref-4) xxxxxx xxxx xxxxxxx xxxxxxxxxxx xxx xxxxxxxx xxxxxxxx
:
@ dccbc75 2h (> master) xxxxxxxxxx xxxxxx xxxxx xxxxxxx
|\
| o a141bba 3m xxxxxxxx xxxxxxxx xxxxxx xxxxx
| |
| o 14ccb65 3m xxxxxx xxxx xxxxxxxxxxx xx xxxxxxxxxxxxx xx xxxxx
| |
| o 544a41d 3m (redacted-ref-0) xxxx xxxxxxxxxx xxxxxxxxxx xxxx xxxxxxxxxx
|\
| o 2445452 2m xxx
|\
| o 4931995 2m (redacted-ref-5) xxxxx xxxxxxxxxxxx xx xxxxxxxxx xxx xxxxxxx xxx xxxx
|\
| o 6573850 2m xxx xxxx xxxxx xxx xxxxxxx xxxxxx xxxxxx
|\
| o 71f2cb3 2m xxxxxxxxx xxxxx xxxxx xxxxxxxxxxxxxx
|\
| o b2b627a 2m (redacted-ref-6) xxxx xxxxxx xx xxxxxxxxxxxxxx
|\
| o b77c2b2 2m xxxxxxxxxxxx xxxxxx xxxx
|\
| o cb3d04e 2m xxxx xxxxx xxxxxxxxxxxxx
|
o dc15639 2m (redacted-ref-7) xxxxxxxxxxxx xxxxxxx xxx
```
##### Event ID: 35281, transaction ID: 33684 (message: hook-post-rewrite)

1. `CommitEvent { timestamp: 1724239239.944935, event_tx_id: Id(33684), commit_oid: NonZeroOid(a141bbacba50eb67232f43bae6b4b00afb1253b9) }`
1. `CommitEvent { timestamp: 1724239239.944935, event_tx_id: Id(33684), commit_oid: NonZeroOid(14ccb65e670d2657c65ab840159c835cb95895d6) }`
1. `CommitEvent { timestamp: 1724239239.944935, event_tx_id: Id(33684), commit_oid: NonZeroOid(544a41dce571419d530d0f96f61f698aeee424c3) }`
1. `RewriteEvent { timestamp: 1724239239.944935, event_tx_id: Id(33684), old_commit_oid: db86ca859aa3861bd81473198fc610849b174a50, new_commit_oid: a141bbacba50eb67232f43bae6b4b00afb1253b9 }`
1. `RewriteEvent { timestamp: 1724239239.944935, event_tx_id: Id(33684), old_commit_oid: c1aeb86efb5362dacd522e49cd18862eb3204cdb, new_commit_oid: 14ccb65e670d2657c65ab840159c835cb95895d6 }`
1. `RewriteEvent { timestamp: 1724239239.944935, event_tx_id: Id(33684), old_commit_oid: 9f2cb6e9dc54b267dffa7cd61c5a5000484e0e56, new_commit_oid: 544a41dce571419d530d0f96f61f698aeee424c3 }`
```
:
O 773160d 5d (redacted-ref-1) xxx xxxx xxxxx xx xxxxx xxxxxx xxxx
:
O 63c012d 5d (redacted-ref-2) xxx x xxxxxxx xxxxxxxxxxx xxxx
:
O f04467d 4d (redacted-ref-3) xxx xxx
:
O f3d9e38 1d (redacted-ref-4) xxxxxx xxxx xxxxxxx xxxxxxxxxxx xxx xxxxxxxx xxxxxxxx
:
@ dccbc75 2h (> master) xxxxxxxxxx xxxxxx xxxxx xxxxxxx
|\
| o a141bba 3m xxxxxxxx xxxxxxxx xxxxxx xxxxx
| |
| o 14ccb65 3m xxxxxx xxxx xxxxxxxxxxx xx xxxxxxxxxxxxx xx xxxxx
| |
| o 544a41d 3m (redacted-ref-0) xxxx xxxxxxxxxx xxxxxxxxxx xxxx xxxxxxxxxx
|\
| o 2445452 2m xxx
|\
| o 4931995 2m (redacted-ref-5) xxxxx xxxxxxxxxxxx xx xxxxxxxxx xxx xxxxxxx xxx xxxx
|\
| o 6573850 2m xxx xxxx xxxxx xxx xxxxxxx xxxxxx xxxxxx
|\
| o 71f2cb3 2m xxxxxxxxx xxxxx xxxxx xxxxxxxxxxxxxx
|\
| o b2b627a 2m (redacted-ref-6) xxxx xxxxxx xx xxxxxxxxxxxxxx
|\
| o b77c2b2 2m xxxxxxxxxxxx xxxxxx xxxx
|\
| o cb3d04e 2m xxxx xxxxx xxxxxxxxxxxxx
|
o dc15639 2m (redacted-ref-7) xxxxxxxxxxxx xxxxxxx xxx
```
##### Event ID: 35280, transaction ID: 33682 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1724239239.859928, event_tx_id: Id(33682), ref_name: ReferenceName("refs/heads/redacted-ref-0"), old_oid: 9f2cb6e9dc54b267dffa7cd61c5a5000484e0e56, new_oid: 544a41dce571419d530d0f96f61f698aeee424c3, message: None }`
```
:
O 773160d 5d (redacted-ref-1) xxx xxxx xxxxx xx xxxxx xxxxxx xxxx
:
O 63c012d 5d (redacted-ref-2) xxx x xxxxxxx xxxxxxxxxxx xxxx
:
O f04467d 4d (redacted-ref-3) xxx xxx
:
O f3d9e38 1d (redacted-ref-4) xxxxxx xxxx xxxxxxx xxxxxxxxxxx xxx xxxxxxxx xxxxxxxx
:
@ dccbc75 2h (> master) xxxxxxxxxx xxxxxx xxxxx xxxxxxx
|\
| o a141bba 3m xxxxxxxx xxxxxxxx xxxxxx xxxxx
| |
| o 14ccb65 3m xxxxxx xxxx xxxxxxxxxxx xx xxxxxxxxxxxxx xx xxxxx
| |
| o 544a41d 3m (redacted-ref-0) xxxx xxxxxxxxxx xxxxxxxxxx xxxx xxxxxxxxxx
|\
| o 2445452 2m xxx
|\
| o 4931995 2m (redacted-ref-5) xxxxx xxxxxxxxxxxx xx xxxxxxxxx xxx xxxxxxx xxx xxxx
|\
| o 6573850 2m xxx xxxx xxxxx xxx xxxxxxx xxxxxx xxxxxx
|\
| o 71f2cb3 2m xxxxxxxxx xxxxx xxxxx xxxxxxxxxxxxxx
|\
| o b2b627a 2m (redacted-ref-6) xxxx xxxxxx xx xxxxxxxxxxxxxx
|\
| o b77c2b2 2m xxxxxxxxxxxx xxxxxx xxxx
|\
| o cb3d04e 2m xxxx xxxxx xxxxxxxxxxxxx
|
o dc15639 2m (redacted-ref-7) xxxxxxxxxxxx xxxxxxx xxx
```

</details>

**Comment by niklaskorz** [comment]
Tried both git 2.44.1 and 2.46.0. This bug only occurs on 2.46.0

**Comment by chrisdoherty4** [comment]
2.45.2 is also working. 

MacOS 14.6.1 (Apple Silcon)

**Comment by arxanas** [comment]
This was fixed in https://github.com/arxanas/git-branchless/pull/1322 and should be available if you build from `master`. It still needs to be released.
