### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by pwnorbitals** [arxanas/git-branchless#16]
This is the error I get when trying to install through Cargo on Windows 10. Is there any way to troubleshoot this error ? Thanks

<details>
<summary>Details</summary>

```
error: failed to run custom build command for `ncurses v5.101.0`

Caused by:
  process didn't exit successfully: `C:\Users\decla\AppData\Local\Temp\cargo-install0KOJbC\release\build\ncurses-198b7c22f92c184a\build-script-build` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `git-branchless v0.3.1`, intermediate artifacts can be found at `C:\Users\decla\AppData\Local\Temp\cargo-install0KOJbC`

Caused by:
  build failed
```

</details>

**Comment by arxanas** [comment]
@pwnorbitals Thanks for raising this. It should be solved by @waych's #13. Since the fix hasn't been released to Cargo, you can instead install it directly from source with `cargo install --git https://github.com/arxanas/git-branchless`.

**Comment by pwnorbitals** [comment]
Thank you very much with your quick response !

**Comment by waych** [comment]
@pwnorbitals FYI I just sent out another PR which fixes various test and execution issues on Windows.  See PR #20.
