### ISSUE TITLE
Support moving individual commits without their descendants

### ISSUE THREAD

**Issue by arxanas** [arxanas/git-branchless#176]
This functionality could be exposed via something like `git move --exact <commit> --dest <commit>`. More important, this is necessary infrastructure to implement some form of interactive rebase.

**Comment by claytonrcarter** [comment]
Yes, please! I found myself craving this today. I had assembled 2 different branches which each had related commits in them, and I wanted to take those branches apart and reassemble them into ~3 different branches. This was totally possible, but involved a lot of switching back and for between branches, cherry picking, then interactive rebasing to drop the old commits, etc. A way to perform in-memory moves of specific commits from one branch to another would have been great!

**Comment by claytonrcarter** [comment]
FWIW I have some draft code locally that implements this. It's based on the code in #400, and would be happy to polish it off and submit it once that is merged.

**Comment by arxanas** [comment]
@claytonrcarter That would be great! I haven't started work on this at all.
