### ISSUE TITLE
Improve "move" error messaging when it's unable to checkout the updated commit

### ISSUE THREAD

**Issue by bcongdon** [arxanas/git-branchless#181]
### Steps to reproduce
If you have a dirty working copy, running `git move` can successfully "move" the commit, but fail to checkout the new commit, leaving you on the old original commit. 

```
mkdir repo && cd repo && git init
git commit --allow-empty -m "Initial commit" && git branchless init
echo "contents 1" > file1.txt
git add file1.txt && git commit -m "file1"
echo "contents 2" > file2.txt
git add file2.txt && git commit -m "file2"
echo "updated" > file1.txt
git move -s HEAD -d HEAD^^
```

### Expected behavior
The move should fail in a more obvious way, and/or make me pass a flag indicating that I know I'm trying to 'move' a commit with a dirty working copy.

### Actual behavior

```
$ git move -s HEAD -d HEAD^^
Attempting rebase in-memory...
[1/1] Committed as: ab56ac59 file2
branchless: processing 1 update: branch main
branchless: processing 1 rewritten commit
branchless: running command: git checkout main
error: Your local changes to the following files would be overwritten by checkout:
        file1.txt
Please commit your changes or stash them before you switch branches.
Aborting
In-memory rebase succeeded.
```

Since the last line of this message is "In-memory rebase succeeded.", it's not immediately clear that a failure occured.

Smartlog:
```
O 78656746 3m Initial commit
|\
| o 9f601677 3m file1
| |
| % 80147e6e 3m (rewritten as ab56ac59) file2
|
O ab56ac59 3m (main) file2
```

### System configuration
**Rust version**:
rustc 1.55.0 (c8dfcfe04 2021-09-06)

**git-branchless version**:
git-branchless 0.3.7

**Comment by arxanas** [comment]
As of #187, there's a red piece of output saying that the check out failed. Should we consider this issue resolved?

**Comment by bcongdon** [comment]
SGTM
