### ISSUE TITLE
Strange formatting when updating already-present hook

### ISSUE THREAD

**Issue by KevinWuWon** [arxanas/git-branchless#188]
### Description of the bug

On a repo that already has a post-commit hook, run `git branchless init`

```
git init
echo '#!/bin/sh' > .git/hooks/post-commit
git branchless init --main-branch master
```

It fails to install the hook when there already is one.

### Expected behavior

Expect hook to be installed:

```
$ cat .git/hooks/post-commit
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-commit "$@"
## END BRANCHLESS CONFIG
```

### Actual behavior

Hook is not installed

```
$ cat .git/hooks/post-commit
#!/bin/sh
```

### Version of `git-branchless`

git-branchless 0.3.7

**Comment by arxanas** [comment]
Hi @KevinWuWon, thanks for the report. This might already have been fixed in #155. Can you try installing from source and see if the issue persists? (`cargo install --locked --git https://github.com/arxanas/git-branchless`)

**Comment by KevinWuWon** [comment]
Thanks!

It works, but formatting is a bit weird:

```
#!/bin/sh
## START BRANCHLESS CONFIG

        git branchless hook-post-merge "$@"
        ## END BRANCHLESS CONFIG
```

**Comment by arxanas** [comment]
It looks like this is specific to the `post-merge` hook.
