### ISSUE TITLE
test command::test_undo::test_undo_doesnt_make_working_dir_dirty is flaky

### ISSUE THREAD

**Issue by waych** [arxanas/git-branchless#19]
FYI.  Just witnessed this test flake once while running `cargo test` on Debian. May be an issue re granularity of timestamps?

**Comment by arxanas** [comment]
I've seen this test flake before, but I haven't been able to to get it to flake lately. If you see it often, we can disable/delete the test.

**Comment by arxanas** [comment]
Oh, by chance did you run `git commit -a`? I noticed that it only fails in that case, but not when you run `git add` and then `git commit`.
