### ISSUE TITLE
Documenting Git Version Upgrade

### ISSUE THREAD

**Issue by mslinn** [arxanas/git-branchless#21]
The installation docs detail the version of git very well, but not what to do if git needs to be upgraded. For Ubuntu and other Debian derivatives, this is:

```
# For most Ubuntu installations:
sudo add-apt-repository ppa:git-core/ppa
# For WSL this works better:
sudo add-apt-repository 'deb http://ppa.launchpad.net/git-core/ppa/ubuntu groovy main'

sudo apt update
sudo apt install git
```

**Comment by arxanas** [comment]
@mslinn Thanks for the feedback. I separated out the Git compatibility page from the general installation instructions and added instructions to upgrade Git for those platforms: https://github.com/arxanas/git-branchless/wiki/Git-compatibility. Let me know if you think of anything else I should add, or feel free to make a change yourself.
