### ISSUE TITLE
flake: test_undo_hide

### ISSUE THREAD

**Issue by waych** [arxanas/git-branchless#23]
Just noticed this.  Happened on a run of run-tests against git `2.29.2`.

https://github.com/waych/git-branchless/runs/2898734801 

May be related to the `commit -a` observation?

```
---- command::test_undo::test_undo_hide stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: undo_hide-5
Source: tests/command/test_undo.rs:282
-old snapshot
+new results
────────────────────────────────────────────────────────────────────────────────
stdout
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ O f777ecc9 (master) create initial.txt
    1     1 │ |\
    2       │-| o 62fc20d2 (test1) create test1.txt
          2 │+| @ 62fc20d2 (test1) create test1.txt
    3     3 │ |
    4       │-@ fe65c1fe create test2.txt
          4 │+o fe65c1fe create test2.txt
────────────┴───────────────────────────────────────────────────────────────────
thread 'command::test_undo::test_undo_hide' panicked at 'snapshot assertion for 'undo_hide-5' failed in line 282', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.7.1/src/runtime.rs:1036:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    command::test_undo::test_undo_hide
```

**Comment by arxanas** [comment]
The commit children in the graph are stored as a HashSet. For this reason and other reasons, it should be changed to a Vec and sorted using a uniform ordering. Thanks for reporting.

**Comment by arxanas** [comment]
Oh, maybe this ain't that issue. I thought the children nodes were rendered in a different order, but it looks like the checked out commit is different instead. I haven't seen this flake before.

**Comment by waych** [comment]
Not sure if this adds anything useful, but this was also in the log:

```
test command::test_undo::test_undo_hide ... FAILED
Previous HEAD position was fe65c1f create test2.txt
Error: Processing reference-transaction hook

Caused by:
    0: Getting `git2::Repository` for repo
    1: Git error NotFound: could not find repository from '/tmp/.tmpKGoiuN'
branchless: Failed to process reference transaction!
branchless: Some events (e.g. branch updates) may have been lost.
branchless: This is a bug. Please report it.
```

**Comment by arxanas** [comment]
Good news — it reliably fails in CI 😂

**Comment by arxanas** [comment]
I think the problem is lines like this:

https://github.com/arxanas/git-branchless/blob/50343f9f853b3a52b798c5ee6e6b52f792914470/tests/command/test_undo.rs#L54

Setting the working directory or environment variables affects the entire process, so tests running in different threads can clobber each other. We're probably running random `git` commands in the wrong repository occasionally. (As the code is written currently, it should only apply to times where we shell out to `run_git`, which is most prominent in the `undo` command, as it runs `git checkout`.)

I suppose the fix is to manually pass the correct working directory and environment variables to all of the functions which need them.

**Comment by waych** [comment]
Does it make sense to invest in making `git-branchless` thread-safe internally as a library if it is expected to be used as a binary?  Or are you expecting to make this consumable as a threadsafe library as well?

Seems easier to just serialize the tests by either setting RUST_TEST_THREADS=1 in the meantime.

**Comment by arxanas** [comment]
There have already been a couple of bugs/pieces of tricky code arising from implicitly-inherited environments, so this will probably improve clarity in the codebase anyways.

**Comment by arxanas** [comment]
I hope that this has been resolved. If you see it again, then re-open the issue.
