### ISSUE TITLE
git restack doesn't follow branch, stays on previous commit

### ISSUE THREAD

**Issue by kevincox** [arxanas/git-branchless#236]
### Description of the bug

When running `git restack` on the branch of a "child" commit the working directory is left on the old commit.

<pre><span style="background-color:#171421"><font color="#C01C28">130</font></span><span style="background-color:#171421"> ~/git-repo#deploy-docker </span>
<span style="background-color:#171421"><font color="#8B8A88">14:58:14%</font></span><span style="background-color:#171421"><b> gs deploy-a-thing</b></span>
Switched to branch &apos;deploy-a-thing&apos;
branchless: processing checkout
<span style="background-color:#171421"><font color="#26A269">0</font></span><span style="background-color:#171421"> ~/git-repo#deploy-a-thing </span>
<span style="background-color:#171421"><font color="#8B8A88">14:58:19%</font></span><span style="background-color:#171421"><b> git sl</b></span>
⋮
┣━┓
┃ ✕ <font color="#A2734C">4f28f624</font> <font color="#26A269">1h</font> <font color="#5E5C64">(rewritten as 8725c6c3)</font> <font color="#33DA7A">(deploy-apiserver)</font> Move docker build into deploy.
┃ ┃
┃ <b>● </b><font color="#A2734C"><b>6c6d2b69</b></font><b> </b><font color="#26A269"><b>30s</b></font><b> </b><font color="#33DA7A"><b>(deploy-a-thing)</b></font><b> Deploy a-thing using deploy.sh.</b>
┣━┓
┃ ◯ <font color="#A2734C">b901bef6</font> <font color="#26A269">6m</font> <font color="#33DA7A">(deploy-summary)</font> Add summary of &quot;interesting&quot; jobs at the end of the run.
┣━┓
┃ ◯ <font color="#A2734C">8725c6c3</font> <font color="#26A269">9s</font> <font color="#33DA7A">(deploy-docker)</font> Move docker build into deploy.
┃
◇ <font color="#A2734C">011e607f</font> <font color="#26A269">55m</font> <font color="#33DA7A">(remote u/master)</font> Fix pubsub class (#2475)
<span style="background-color:#171421"><font color="#26A269">0</font></span><span style="background-color:#171421"> ~/git-repo#deploy-a-thing </span>
<span style="background-color:#171421"><font color="#8B8A88">14:58:25%</font></span><span style="background-color:#171421"><b> git restack</b></span>
Attempting rebase in-memory...
[1/1] Committed as: <font color="#A2734C">b2133f26</font> Deploy a-thing using deploy.sh.
branchless: processing 1 update: branch deploy-a-thing
branchless: processing 1 rewritten commit
<font color="#8B8A88">branchless: running command: git checkout deploy-a-thing</font>
<font color="#8B8A88">Previous HEAD position was 6c6d2b69d Deploy a-thing using deploy.sh.</font>
<font color="#8B8A88">Switched to branch &apos;deploy-a-thing&apos;</font>
<font color="#8B8A88">branchless: processing checkout</font>
In-memory rebase succeeded.
Finished restacking commits.
branchless: processing 1 update: branch deploy-apiserver
Finished restacking branches.
<font color="#8B8A88">branchless: running command: git checkout 6c6d2b69d7efa4b02b4fbe42c7c7ae80ab6af8b8</font>
<font color="#8B8A88">branchless: processing 1 update: ref HEAD</font>
<font color="#8B8A88">HEAD is now at 6c6d2b69d Deploy a-thing using deploy.sh.</font>
<font color="#8B8A88">branchless: processing checkout</font>
⋮
┣━┓
┃ ✕ <font color="#A2734C">4f28f624</font> <font color="#26A269">1h</font> <font color="#5E5C64">(rewritten as 8725c6c3)</font> Move docker build into deploy.
┃ ┃
┃ <b>⦻ </b><font color="#A2734C"><b>6c6d2b69</b></font><b> </b><font color="#26A269"><b>37s</b></font><b> </b><font color="#5E5C64"><b>(rewritten as b2133f26)</b></font><b> Deploy a-thing using deploy.sh.</b>
┣━┓
┃ ◯ <font color="#A2734C">b901bef6</font> <font color="#26A269">7m</font> <font color="#33DA7A">(deploy-summary)</font> Add summary of &quot;interesting&quot; jobs at the end of the run.
┣━┓
┃ ◯ <font color="#A2734C">8725c6c3</font> <font color="#26A269">16s</font> <font color="#33DA7A">(deploy-apiserver, deploy-docker)</font> Move docker build into deploy.
┃ ┃
┃ ◯ <font color="#A2734C">b2133f26</font> <font color="#26A269">1s</font> <font color="#33DA7A">(deploy-a-thing)</font> Deploy a-thing using deploy.sh.
┃
◇ <font color="#A2734C">011e607f</font> <font color="#26A269">55m</font> <font color="#33DA7A">(remote u/master)</font> Fix pubsub class (#2475)
<span style="background-color:#171421"><font color="#26A269">0</font></span><span style="background-color:#171421"> ~/git-repo#branchless/6c6d2b69d7efa4b02b4fbe42c7c7ae80ab6af8b8 </span>
<span style="background-color:#171421"><font color="#8B8A88">14:58:48%</font></span><span style="background-color:#171421"><b> </b></span>
</pre>

Log edited to remove sensitive info, may not be perfectly accurate to a simple case. However it seems to happen every time I do this so it is hopefully not too hard to reproduce.

`git undo` log:

<pre>┌──────────────────────────────────────────────────┤ Events ├──────────────────────────────────────────────────┐
│Repo after transaction 288 (event 331) (10m ago). Press &apos;h&apos; for help, &apos;q&apos; to quit.                            │
│1. Move branch deploy-a-thing from <font color="#A2734C">6c6d2b69</font> Deploy a-thing using deploy.sh.                      │
│                                    to <font color="#A2734C">b2133f26</font> Deploy a-thing using deploy.sh.                      │
│2. Rewrite commit <font color="#A2734C">6c6d2b69</font> Deploy a-thing using deploy.sh.                                                │
│              as <font color="#A2734C">b2133f26</font> Deploy a-thing using deploy.sh.                                                 │
│3. Check out from <font color="#A2734C">6c6d2b69</font> Deploy a-thing using deploy.sh.                                                │
│               to <font color="#A2734C">b2133f26</font> Deploy a-thing using deploy.sh.                                                │
│4. Move branch deploy-apiserver from <font color="#A2734C">4f28f624</font> Move docker build into deploy.                             │
│                                  to <font color="#A2734C">8725c6c3</font> Move docker build into deploy.                             │
│5. Check out to <font color="#A2734C">6c6d2b69</font> Deploy a-thing using deploy.sh.                                                  │
│                                                                                                              │
│6. Check out from <font color="#A2734C">b2133f26</font> Deploy a-thing using deploy.sh.                                                │
│               to <font color="#A2734C">6c6d2b69</font> Deploy a-thing using deploy.sh.                                                │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
</pre>

See https://github.com/arxanas/git-branchless/discussions/228 for original report.

### Expected behavior

After running `git restack` in the `deploy-a-thing` branch (which has an outdated parent) I would expect to still be on the `deploy-a-thing` branch with the updated commit.

### Actual behavior

The branch follows the updated commit but the local checkout switches to `branchless/6c6d2b69d7efa4b02b4fbe42c7c7ae80ab6af8b8` instead of the `deploy-a-thing` branch (which is on the old commit).

### Version of `git-branchless`

git-branchless 0.3.7

### Version of `rustc`

rustc 1.56.1

**Comment by arxanas** [comment]
Thanks for the details, I was able to reproduce this.
