### ISSUE TITLE
Sometimes a branch name is moved during amend operations.

### ISSUE THREAD

**Issue by jacobsimpson-addepar** [arxanas/git-branchless#253]
### Description of the bug

I've encountered a situation where I do amend or rebase operations and the branch name ends up on a different commit than expected.

For example, if I start with this:

```
$ git smartlog
◇ 85543e73 9m (master, remote origin/master) Initial commit.
┃
● a4dd2541 9m (feature-1) Update line 2.
┃
◯ eacd5224 9m (feature-2) Make line 2 extra verbose
```

and I amend something (`git commit --amend`) to the `feature-1` branch, I get this:

```
$ git smartlog
◇ 85543e73 8m (master, remote origin/master) Initial commit.
┃
● c3da2846 7m Update line 2.
┃
◯ efcc9993 7m (feature-1, feature-2) Make line 2 extra verbose
```

where I would hope to get this:

```
$ git smartlog
◇ 85543e73 8m (master, remote origin/master) Initial commit.
┃
● c3da2846 7m (feature-1) Update line 2.
┃
◯ efcc9993 7m (feature-2) Make line 2 extra verbose
```

I don't have a good understanding of all the circumstances where I am seeing this, however I've attached a small script that replicates the behavior that I'm seeing. I'm using:

```
$ git-branchless --version
git-branchless 0.3.8
```

```
#! /bin/bash

#
# Create origin repo.
#
mkdir -p origin-repo
cd origin-repo
git init .
printf "one\ntwo\nthree\n" > README.md
git add .
git commit -am "Initial commit."
cd ..

#
# Clone the origin repo.
#
git clone origin-repo/.git cloned-repo

#
# Configure with branchless extensions.
#
cd cloned-repo
git branchless init

#
# Make branch feature-1 with a change.
#
git checkout -b feature-1
cp README.md tmp && sed '2s/^/lin /' < tmp > README.md && rm tmp
git commit -am "Update line 2."

#
# Make a branch feature-2, stacked on feature-1, with a change on the same line.
#
git checkout -b feature-2
cp README.md tmp && sed '2s/^/this is /' < tmp > README.md && rm tmp
git commit -am "Make line 2 extra verbose"

#
# Go back to the feature-1 branch and make a conflicting change.
#
git ch feature-1
cp README.md tmp && sed '2s/^lin /line /' < tmp > README.md && rm tmp
git amend -a

# This step will cause a conflict, so the --merge flag is necessary.
git restack --merge

# Resolve the conflict.
printf "one\nthis is line two\nthree" > README.md
git add README.md
GIT_EDITOR=true git rebase --continue
```

### Expected behavior

```
$ git smartlog
◇ 85543e73 8m (master, remote origin/master) Initial commit.
┃
● c3da2846 7m (feature-1) Update line 2.
┃
◯ efcc9993 7m (feature-2) Make line 2 extra verbose
```

### Actual behavior

```
$ git smartlog
◇ 85543e73 8m (master, remote origin/master) Initial commit.
┃
● c3da2846 7m Update line 2.
┃
◯ efcc9993 7m (feature-1, feature-2) Make line 2 extra verbose
```

### Version of `git-branchless`

git-branchless 0.3.8

### Version of `rustc`

rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by arxanas** [comment]
@jacobsimpson-addepar Thanks for the report. This issue looks similar to https://github.com/arxanas/git-branchless/issues/249. Can you try installing the latest git-branchless from source and see if the issue persists?

FYI, git-branchless may have overwritten your `git amend` alias (if you had one) — it won't have the same behavior as `git commit --amend`. It should no longer do so (https://github.com/arxanas/git-branchless/issues/219) but it's possible that you installed a version from source in between versions which did overwrite your user alias.

**Comment by jacobsimpson-addepar** [comment]
I compiled the latest version from source and re-ran my test case. I see the expected behavior now. Looks good to me.

Thanks for the FYI about `amend`. I'll verify that I'm getting the expected behavior.
