### ISSUE TITLE
Deleted branch is constantly recreated

### ISSUE THREAD

**Issue by FliegendeWurst** [arxanas/git-branchless#257]
### Description of the bug

First, I manually deleted a branch: `git branch -D name-a`

Then, I performed a rebase on an unrelated branch and got this output:
```
branchless: processing 1 update: branch name-b
branchless: processing 2 rewritten commits
branchless: This operation abandoned 1 branch (name-a)!
```
And suddenly `name-a` existed again..

### Expected behavior

git-branchless shouldn't recreate branches I deleted.

### Version of `git-branchless`

git-branchless 0.3.7

### Version of `git`

2.33.1

**Comment by arxanas** [comment]
Hi @FliegendeWurst, thanks for your report. This might be the same issue as #149. Can you check the contents of `.git/ORIG_HEAD` and post them here? It's possible that it erroneously contains a symbolic reference (a line starting with `ref: `) which causes this behavior. If so, try deleting that file and upgrading to v0.3.8, which should fix the problem.

**Comment by FliegendeWurst** [comment]
Yes, that file contains a symbolic refence. Deleting the file and updating fixed the issue :)
