### ISSUE TITLE
Hardcoded paths in tests

### ISSUE THREAD

**Issue by nh2** [arxanas/git-branchless#26]
Hi, I'm trying to package `git-branchless` for [nixpkgs](https://github.com/NixOS/nixpkgs/) (here: https://github.com/NixOS/nixpkgs/pull/127971), which installs all packages in completely separate prefixes, and thus `/bin` or `/usr/bin` don't exist.

I found the following two hardcodes that make that difficult:

* `/bin/echo` in `src/commands/wrap.rs`
* `/usr/bin/true` in tests, that was just fixed in https://github.com/arxanas/git-branchless/pull/20#discussion_r657529101
* `/usr/bin/git` in the tests in `src/testing.rs`
  * For this one it isn't quite clear to me why it exists at all, given that other places in the same file use the `PATH_TO_GIT` environment variable

Do you think it would be possible to take these commands from `PATH` instead of hardcoded absolute paths, so that code and tests run unpatched in all environments?

Thanks!

**Comment by arxanas** [comment]
Yes, I can look into this.

**Comment by arxanas** [comment]
@nh2: I committed #27, does that solve the remaining issues?

**Comment by nh2** [comment]
@arxanas Yes, I tested it, it solves them, thank you!
