### ISSUE TITLE
Test suite Git usage unorthodox enough to be troublesome

### ISSUE THREAD

**Issue by alerque** [arxanas/git-branchless#266]
Setting up [Arch Linux packaging](https://aur.archlinux.org/packages/git-branchless) for this I ran into problems running the test suite via `cargo test`. I am building in a clear chroot with *just* the required dependencies available so nothing too messing going on on the system.

First, the need to specify the path to Git is pretty bizarre. Needing to have the `git` binary for the test suite is fine, but it should default to just using the bare binary name and not worrying about the systems `$PATH`. The fact that `export PATH_TO_GIT=$(which git)` makes it function should be a sign that just using `git` in the first place would have worked. Instead an *override* variable could be used to specify a path other than the system default for special testing scenarios.

Second, even after setting the path variable as above, at least one of the tests is failing with a strange error indeed:

```
Error: Git command "/usr/bin/git" ["bisect", "start"] exited with unexpected code 1 (expected 0)
                stdout:

                stderr:
                git: 'bisect' is not a git command. See 'git --help'.
```

The `git bisect` subcommand works just fine from the system's `git` (yes, the one at `/usr/bin/git`) so I have no idea how this error could have been triggered. Not by calling `git bisect start` evidently, perhaps it is short circuiting the process and assuming `git-bisect start`? Just a guess, but something isn't right here.

### Version of `git-branchless`

0.3.9

### Version of `git`

2.35.1

### Version of `rustc`

1.57.0

**Comment by arxanas** [comment]
Will respond with some more detail later. `git bisect` is not written in C and not built into the Git executable. You need to include `git-bisect` and the other executables associated with Git (like `git receive-pack` maybe?) in your chroot. See also `GIT_EXEC_PATH ` env var and command `git --exec-path`

**Comment by alerque** [comment]
The executable for git-bisect (or rather shell script wrapper and helper binary) are already included in the chroot (they come with Arch Linux's `git` package). If you login to the chroot in an empty shell with the default path running `git bisect` is able to execute them just fine.

**Comment by arxanas** [comment]
Can you try setting the `GIT_EXEC_PATH` env var as part of your test invocation? Most env vars are cleared out, but that one is specifically passed through. See also `testing.rs` for the details on env handling

**Comment by alerque** [comment]
This does get through the testing phase:

```bash
export PATH_TO_GIT=$(which git) GIT_EXEC_PATH=$(git --exec-path)
cargo test --frozen --all-features
```

That pair of exports should be completely unnecessary, the only time those should need to be set is when the test runner wants to use something *other than* the system default executables for whatever reason.

**Comment by arxanas** [comment]
In principle I agree that these should be opt-in overrides, but collaborators and I have spent unreasonable amounts of time debugging environment issues, so I made them required. To hopefully avoid confusion in the future, I changed the test-related environment variables to start with `TEST_` and be uniformly mandatory.

**Comment by claytonrcarter** [comment]
The [Runbook](https://github.com/arxanas/git-branchless/wiki/Runbook) appears to need an update, too. It wasn't immediately clear to me how to set `TEST_GIT` and `TEST_GIT_EXEC_PATH`. The error messages in the tests were helpful, but I ultimately figured it out by looking at the CI workflows. For anyone else, `TEST_GIT` needs to be set to the output of `which git` and `TEST_GIT_EXEC_PATH` needs to be set to the output of `git --exec-path`. These happen either in your shell (ie `export TEST_GIT=$(which git)` or (for us fish users) `set -s TEST_GIT (which git)`) or in `.cargo/config.toml`, under an `[env]` section). In my case, this is my `.cargo/config.toml`:
```toml
[env]
TEST_GIT = "/usr/local/bin/git"
TEST_GIT_EXEC_PATH = "/usr/local/Cellar/git/2.32.0_1/libexec/git-core"
```

Sorry if this is obvious to others. I'm learning rust (and toml) as I go here. 😄

**Comment by arxanas** [comment]
@claytonrcarter thanks for raising; I updated the Runbook.
