### ISSUE TITLE
Use git2 hash-shortening function

### ISSUE THREAD

**Issue by arxanas** [arxanas/git-branchless#280]
### Discussed in https://github.com/arxanas/git-branchless/discussions/279

<div type='discussions-op-text'>

<sup>Originally posted by **KevinWuWon** February 21, 2022</sup>
A few times, the 8-character hash has been too short and it has given me a collision. It's quite annoying when this happens because it just gives me an error message like:

```
Git error Ambiguous: ambiguous SHA1 prefix - multiple matches for prefix: 1e0397ec4cc2148c6587e30bc85baae8b3f26002 1e0397ecb633e9115514b7c256560ddc27594289
```

and I still don't know which one I want.

My two feature requests are:

1. in this error message, print also the commit title so I can tell them apart
2. give an option to increase the default hash prefix length to display in `git sl`</div>

**Comment by yujong-lee** [comment]
@arxanas  Maybe we can close it by #306?

**Comment by arxanas** [comment]
@yujong-lee yes, thanks for fixing this!
