### ISSUE TITLE
passing args to `git` when `git` is aliased to `git-branchless wrap`

### ISSUE THREAD

**Issue by claytonrcarter** [arxanas/git-branchless#307]
### Description of the bug

`git` supports a number of flags passed directly to it (ie not flags passed to a subcommand), but when `git` is aliased to `git-branchless wrap`, these appear to be swallowed by `git-branchless`, which then chokes on them. 😄 

For example, none of the following commands succeed:
```
❯ git --version
❯ git --help
❯ git --no-pager branch --format='%(refname:short)'
❯ git --no-pager diff main
```

Using `git -- <args...>` is a workaround. All of these succeed:
```
❯ git -- --version
❯ git -- --help
❯ git -- --no-pager branch --format='%(refname:short)'
❯ git -- --no-pager diff main
```

Though the workaround is pretty easy, it still feels pretty counterintuitive and surprising for valid, preexisting `git` scripts to stop working after setting up the recommended alias. I don't know if it's relevant, but I'm using fish shell (version 3.3.1).

### Expected behavior

```
❯ git --version
git version 2.32.0

❯ git --help
usage: git ...
...

❯ git --no-pager branch --format='%(refname:short)'
... list of branches ...

❯ git --no-pager diff main
... a diff ...

```

### Actual behavior

All of the above commands something like 
```
❯ git --help
git-branchless-wrap
Wrap a Git command inside a branchless transaction

USAGE:
    git-branchless wrap [OPTIONS] <SUBCOMMAND>

OPTIONS:
        --git-executable <GIT_EXECUTABLE>    The `git` executable to invoke
    -h, --help                               Print help information
```

### Version of `git-branchless`

git-branchless 0.3.9

### Version of `git`

git version 2.32.0

### Version of `rustc`

rustc 1.58.1 (db9d1b20b 2022-01-20)

**Comment by claytonrcarter** [comment]
Aaaaand, nevermind! The workaround is to use `alias git='git-branchless wrap --'` (ie add the `--` into the alias)

**Comment by arxanas** [comment]
Thanks for raising. I've updated the instructions at https://github.com/arxanas/git-branchless/wiki/Installation#installation to include the `--` in the alias. (Actually, this had been bugging me for a while, and I didn't think of that!)
