### ISSUE TITLE
`git reword` doesn't respect git config's `core.editor`

### ISSUE THREAD

**Issue by alan-nf** [arxanas/git-branchless#328]
### Description of the bug

When I `git reword <hash>` vim is used. `EDITOR` is not exported on my machine so this aligns with the documentation.

Note: my simple workaround was: `export EDITOR=<editor> && git reword <hash>`

### Expected behavior

I expect the same editor to be used for `git commit` and `git branchless reword`.

In other words: `$EDITOR` is used as a fallback, but `core.editor` takes precedence.

### Actual behavior

vim opens regardless

### Version of `git-branchless`

restack PR (#326)

### Version of `git`

2.32.0

### Version of `rustc`

1.59.0

**Comment by arxanas** [comment]
Thanks for the report. According to the documentation: https://git-scm.com/docs/git-var#Documentation/git-var.txt-GITEDITOR, it looks like we should be checking configuration in this order:

- `$GIT_EDITOR`
- `core.editor`
- `$VISUAL`
- `$EDITOR`

**Comment by claytonrcarter** [comment]
Yes, thanks for the report and sorry for the oversight. Dialoguer (the lib used to open the editor) [already checks `$VISUAL` and `$EDITOR`](https://github.com/mitsuhiko/dialoguer/blob/master/src/edit.rs#L30-L42=), so we should able to just check the git-specific config.
