### ISSUE TITLE
git-branchless stopped compiling on Rust 1.56.1

### ISSUE THREAD

**Issue by hmenke** [arxanas/git-branchless#363]
### Description of the bug

Looks like you are using the new f-strings. These are only available in Rust 1.58 (I think?)

On Rust 1.56.1 this happens:
```
error: there is no argument named `head_oid`
   --> git-branchless/src/commands/undo.rs:870:33
    |
870 |                 todo!("Use HEAD {head_oid:?}, branch {ref_name:?}, and commit {commit_oid:?} to check out a previous working copy state");
    |                                 ^^^^^^^^^^^^
error: there is no argument named `ref_name`
   --> git-branchless/src/commands/undo.rs:870:54
    |
870 |                 todo!("Use HEAD {head_oid:?}, branch {ref_name:?}, and commit {commit_oid:?} to check out a previous working copy state");
    |                                                      ^^^^^^^^^^^^
error: there is no argument named `commit_oid`
   --> git-branchless/src/commands/undo.rs:870:79
    |
870 |                 todo!("Use HEAD {head_oid:?}, branch {ref_name:?}, and commit {commit_oid:?} to check out a previous working copy state");
    |                                                                               ^^^^^^^^^^^^^^
```

### Expected behavior

It compiles.

### Actual behavior

It does not compile.

### Version of `git-branchless`

Latest HEAD 3595f3d151dffb974f7f6fddb500c79ee25a0431

### Version of `git`

git version 2.33.1

### Version of `rustc`

rustc 1.56.1

**Comment by arxanas** [comment]
Hi @hmenke, thanks for the heads up. I had intended to set 1.56 as the minimum supported Rust version, but it looks like I didn't pin it correctly here:

https://github.com/arxanas/git-branchless/blob/3595f3d151dffb974f7f6fddb500c79ee25a0431/.github/workflows/linux.yml#L73-L77

**Comment by arxanas** [comment]
Should be working now, let me know if it still fails for you.
