### ISSUE TITLE
Tab-completion stopped working

### ISSUE THREAD

**Issue by alan-nf** [arxanas/git-branchless#381]
### Description of the bug

When I do things like `git switch <tab>` it used to tab-complete branch names. That isn't happening anymore for me.

* My git command is aliased to `git-branchless wrap --`
* I'm using zsh
* git-branchless v0.3.12
* tab-completion was working on v0.3.10
* `/usr/bin/git switch <tab>` works fine so that's how I know this is a git-branchless issue

### Expected behavior

`git switch <tab>` should give list of branch names

### Actual behavior

`git switch <tab>` lists files in the current directory

### Version of `git-branchless`

0.3.12

### Version of `git`

2.32.0

### Version of `rustc`

1.59.0

#### Software version

git-branchless 0.3.12

#### Operating system

macOS 12.2.1 (Darwin 21.3.0)

#### Command-line

```bash
/Users/anorbauer/.cargo/bin/git-branchless bug-report 
```

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=emacs
```

#### Git version

```
> git version 
git version 2.32.0 (Apple Git-132)
```

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 2434, transaction ID: 2423

1. `RefUpdateEvent { timestamp: 1651019809.159284, event_tx_id: EventTransactionId(2423), ref_name: "refs/remotes/redacted-ref-0", old_oid: 8ac0db4722c67bc36635f4294d381ededdc0b015, new_oid: be0cb9ea7ff10b5c6b80f7ea285fe57bf4c2fe9a, message: None }`
```
:
O eb2af4b 27d xxxxxxxxxxxxxxxxxxxxxxx xxxxxxx xxxxxx xxxxxxx
|\
: o 90dd15d 27d (redacted-ref-1) xxx x xxxxx xxxxxx xxxxxxxxxxxxxxx xxxxxx
:
O d1d92ac 8d xxxxxxx xxxxx xxxx xxxx xx xxxx xxxxxx
|\
: o de1ecb8 8d xxxxxx xxxxxxxxxxx xxxx xxxxxxxxxxx
: |
: o 8513a41 8d xxx xxxxxxxxx xx xxxxxx xxxxx xxxxxxxx
: |
: o 2204aff 8d (redacted-ref-2) xxx xxxx xxxxxxx xx xxxxxx xxxxx xxxxxxxx
:
O de3d242 6d (redacted-ref-3) xxx xxxxx xxxxxxx xxxx xxxxxxx xxxxxxxx xxxxxx
|\
| o 8aaa1c5 6d xxx x xxxx xxxxxxx xxxxxxxxxxx x xxx xx xxxx
|\
: o 95098af 6d xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
:
O 669871a 5d (redacted-ref-4, remote origin/main) xxx xxxx xxxxxx xxxxx
|\
| o 4ccc90d 4d (redacted-ref-5) xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
|\
| o 52d1421 4d (redacted-ref-6) xxxx xxxxxx xxxxxxxxx xxxxx xxxxxxxxxxx
|\
| o 595c91c 4d (redacted-ref-7) xxxx xxxxx xxxx xxxxxxxxxxxx x xxxx xxxxx
|
@ 9f1d0a2 19h (redacted-ref-8) xxx xxxxx xxxxx xx xxxxx xxxxxx
```
##### Event ID: 2433, transaction ID: 2422

1. `RefUpdateEvent { timestamp: 1651019558.182244, event_tx_id: EventTransactionId(2422), ref_name: "refs/remotes/redacted-ref-0", old_oid: 40c184d9c4290ffc42072289da549a81bc77f00f, new_oid: 8ac0db4722c67bc36635f4294d381ededdc0b015, message: None }`
```
:
O eb2af4b 27d xxxxxxxxxxxxxxxxxxxxxxx xxxxxxx xxxxxx xxxxxxx
|\
: o 90dd15d 27d (redacted-ref-1) xxx x xxxxx xxxxxx xxxxxxxxxxxxxxx xxxxxx
:
O d1d92ac 8d xxxxxxx xxxxx xxxx xxxx xx xxxx xxxxxx
|\
: o de1ecb8 8d xxxxxx xxxxxxxxxxx xxxx xxxxxxxxxxx
: |
: o 8513a41 8d xxx xxxxxxxxx xx xxxxxx xxxxx xxxxxxxx
: |
: o 2204aff 8d (redacted-ref-2) xxx xxxx xxxxxxx xx xxxxxx xxxxx xxxxxxxx
:
O de3d242 6d (redacted-ref-3) xxx xxxxx xxxxxxx xxxx xxxxxxx xxxxxxxx xxxxxx
|\
| o 8aaa1c5 6d xxx x xxxx xxxxxxx xxxxxxxxxxx x xxx xx xxxx
|\
: o 95098af 6d xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
:
O 669871a 5d (redacted-ref-4, remote origin/main) xxx xxxx xxxxxx xxxxx
|\
| o 4ccc90d 4d (redacted-ref-5) xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
|\
| o 52d1421 4d (redacted-ref-6) xxxx xxxxxx xxxxxxxxx xxxxx xxxxxxxxxxx
|\
| o 595c91c 4d (redacted-ref-7) xxxx xxxxx xxxx xxxxxxxxxxxx x xxxx xxxxx
|
@ 9f1d0a2 19h (redacted-ref-8) xxx xxxxx xxxxx xx xxxxx xxxxxx
```
##### Event ID: 2431, transaction ID: 2421

1. `RefUpdateEvent { timestamp: 1651018906.087497, event_tx_id: EventTransactionId(2421), ref_name: "HEAD", old_oid: 686e67054508333ce1236f3cfdca45a90e825af0, new_oid: 9f1d0a259740ef084e3bc3de292514349ed3cc2b, message: None }`
1. `RefUpdateEvent { timestamp: 1651018906.087497, event_tx_id: EventTransactionId(2421), ref_name: "refs/heads/redacted-ref-8", old_oid: 686e67054508333ce1236f3cfdca45a90e825af0, new_oid: 9f1d0a259740ef084e3bc3de292514349ed3cc2b, message: None }`
```
:
O eb2af4b 27d xxxxxxxxxxxxxxxxxxxxxxx xxxxxxx xxxxxx xxxxxxx
|\
: o 90dd15d 27d (redacted-ref-1) xxx x xxxxx xxxxxx xxxxxxxxxxxxxxx xxxxxx
:
O d1d92ac 8d xxxxxxx xxxxx xxxx xxxx xx xxxx xxxxxx
|\
: o de1ecb8 8d xxxxxx xxxxxxxxxxx xxxx xxxxxxxxxxx
: |
: o 8513a41 8d xxx xxxxxxxxx xx xxxxxx xxxxx xxxxxxxx
: |
: o 2204aff 8d (redacted-ref-2) xxx xxxx xxxxxxx xx xxxxxx xxxxx xxxxxxxx
:
O de3d242 6d (redacted-ref-3) xxx xxxxx xxxxxxx xxxx xxxxxxx xxxxxxxx xxxxxx
|\
| o 8aaa1c5 6d xxx x xxxx xxxxxxx xxxxxxxxxxx x xxx xx xxxx
|\
: o 95098af 6d xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
:
O 669871a 5d (redacted-ref-4, remote origin/main) xxx xxxx xxxxxx xxxxx
|\
| o 4ccc90d 4d (redacted-ref-5) xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
|\
| o 52d1421 4d (redacted-ref-6) xxxx xxxxxx xxxxxxxxx xxxxx xxxxxxxxxxx
|\
| o 595c91c 4d (redacted-ref-7) xxxx xxxxx xxxx xxxxxxxxxxxx x xxxx xxxxx
|
@ 9f1d0a2 19h (redacted-ref-8) xxx xxxxx xxxxx xx xxxxx xxxxxx
```
##### Event ID: 2429, transaction ID: 2416

1. `RefUpdateEvent { timestamp: 1651018381.557539, event_tx_id: EventTransactionId(2416), ref_name: "HEAD", old_oid: 669871abd06e372578ecfb2527a665f9091a221b, new_oid: 686e67054508333ce1236f3cfdca45a90e825af0, message: None }`
1. `RefUpdateEvent { timestamp: 1651018381.557539, event_tx_id: EventTransactionId(2416), ref_name: "refs/heads/redacted-ref-8", old_oid: 669871abd06e372578ecfb2527a665f9091a221b, new_oid: 686e67054508333ce1236f3cfdca45a90e825af0, message: None }`
```
:
O eb2af4b 27d xxxxxxxxxxxxxxxxxxxxxxx xxxxxxx xxxxxx xxxxxxx
|\
: o 90dd15d 27d (redacted-ref-1) xxx x xxxxx xxxxxx xxxxxxxxxxxxxxx xxxxxx
:
O d1d92ac 8d xxxxxxx xxxxx xxxx xxxx xx xxxx xxxxxx
|\
: o de1ecb8 8d xxxxxx xxxxxxxxxxx xxxx xxxxxxxxxxx
: |
: o 8513a41 8d xxx xxxxxxxxx xx xxxxxx xxxxx xxxxxxxx
: |
: o 2204aff 8d (redacted-ref-2) xxx xxxx xxxxxxx xx xxxxxx xxxxx xxxxxxxx
:
O de3d242 6d (redacted-ref-3) xxx xxxxx xxxxxxx xxxx xxxxxxx xxxxxxxx xxxxxx
|\
| o 8aaa1c5 6d xxx x xxxx xxxxxxx xxxxxxxxxxx x xxx xx xxxx
|\
: o 95098af 6d xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
:
O 669871a 5d (redacted-ref-4, remote origin/main) xxx xxxx xxxxxx xxxxx
|\
| o 4ccc90d 4d (redacted-ref-5) xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
|\
| o 52d1421 4d (redacted-ref-6) xxxx xxxxxx xxxxxxxxx xxxxx xxxxxxxxxxx
|\
| o 595c91c 4d (redacted-ref-7) xxxx xxxxx xxxx xxxxxxxxxxxx x xxxx xxxxx
|
@ 9f1d0a2 19h (redacted-ref-8) xxx xxxxx xxxxx xx xxxxx xxxxxx
```
##### Event ID: 2428, transaction ID: 2412

1. `RefUpdateEvent { timestamp: 1651018174.123659, event_tx_id: EventTransactionId(2412), ref_name: "refs/heads/redacted-ref-8", old_oid: 0000000000000000000000000000000000000000, new_oid: 669871abd06e372578ecfb2527a665f9091a221b, message: None }`
```
:
O eb2af4b 27d xxxxxxxxxxxxxxxxxxxxxxx xxxxxxx xxxxxx xxxxxxx
|\
: o 90dd15d 27d (redacted-ref-1) xxx x xxxxx xxxxxx xxxxxxxxxxxxxxx xxxxxx
:
O d1d92ac 8d xxxxxxx xxxxx xxxx xxxx xx xxxx xxxxxx
|\
: o de1ecb8 8d xxxxxx xxxxxxxxxxx xxxx xxxxxxxxxxx
: |
: o 8513a41 8d xxx xxxxxxxxx xx xxxxxx xxxxx xxxxxxxx
: |
: o 2204aff 8d (redacted-ref-2) xxx xxxx xxxxxxx xx xxxxxx xxxxx xxxxxxxx
:
O de3d242 6d (redacted-ref-3) xxx xxxxx xxxxxxx xxxx xxxxxxx xxxxxxxx xxxxxx
|\
| o 8aaa1c5 6d xxx x xxxx xxxxxxx xxxxxxxxxxx x xxx xx xxxx
|\
: o 95098af 6d xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
:
O 669871a 5d (redacted-ref-4, remote origin/main) xxx xxxx xxxxxx xxxxx
|\
| o 4ccc90d 4d (redacted-ref-5) xxxx x xxxxxx xxx xxxxxxx xxxxxxxxxxx
|\
| o 52d1421 4d (redacted-ref-6) xxxx xxxxxx xxxxxxxxx xxxxx xxxxxxxxxxx
|\
| o 595c91c 4d (redacted-ref-7) xxxx xxxxx xxxx xxxxxxxxxxxx x xxxx xxxxx
|
@ 9f1d0a2 19h (redacted-ref-8) xxx xxxxx xxxxx xx xxxxx xxxxxx
```

</details>

**Comment by arxanas** [comment]
git-branchless (unfortunately) never supported tab-completion; see https://github.com/arxanas/git-branchless/discussions/217. Is it possible that you added the alias at some later point and didn't notice that tab completions stopped working, or perhaps added the `--` later?

Can you try replacing your alias with `git branchless wrap --` instead of `git-branchless wrap --`, or remove the `--`, and see if either of those affect things? Or maybe see this answer: https://unix.stackexchange.com/a/583743?

**Comment by alan-nf** [comment]
> git-branchless (unfortunately) never supported tab-completion;
Oh. Hah.

> Is it possible that you added the alias at some later point and didn't notice that tab completions stopped working, or perhaps added the -- later?
Yes absolutely.

> Can you try replacing your alias with git branchless wrap -- instead of git-branchless wrap --
No change :(

> or remove the --
No change :(

> Or maybe see this answer: https://unix.stackexchange.com/a/583743?
Oh interesting, the OPPOSITE of this answer works for me. If I `setopt completealiases`, autocomplete works. I'm able to autocomplete branch names by typing `git s R<tab>`. I've added `setopt completealiases` to my .zshrc and it looks to be fixed. Thanks @arxanas !
