### ISSUE TITLE
Unhidden commits shouldn't be garbage collected

### ISSUE THREAD

**Issue by AaronLieberman** [arxanas/git-branchless#412]
### Description of the bug

I have several commits that have been hanging around for a month or two. I looked at my smartlog today and found they're now listed as `<garbage collected>`. 

### Expected behavior

I expected them to stay around until I hid them and not be garbage collected.

### Actual behavior

git garbage collection took them and their metadata away and now I don't have record of what was in them. 

### Version of `rustc`

rustc 1.61.0 (fe5b13d68 2022-05-18)

### Version of `git-branchless`

git-branchless 0.3.12

### Version of `git`

git version 2.36.1

**Comment by arxanas** [comment]
Hi @AaronLieberman, sorry to hear that this happened to you ☹️. In principle, git-branchless generates references to keep commits around, so I'm not sure exactly what happened. Do you know if one of the following applied in your situation?

- You didn't run `git branchless init` in your repository. In https://github.com/arxanas/git-branchless/pull/185, I suppressed the generation of GC references in a repository which hasn't been `init`ed, to address https://github.com/arxanas/git-branchless/issues/183. But it looks like the underlying problem, which is that `tig` shows the GC references, seems to have been fixed, so we could revert that change.
- One of these commits was created before `git branchless init`, and you later deleted the branch pointing to that commit. I suppose the GC ref might not have been created in that case.
- You hid the commit, then `git branchless gc` ran at some point, and then you unhid it, but the GC ref wasn't recreated.

**Comment by AaronLieberman** [comment]
Would running git branchless init multiple times be a problem? I've used that to upgrade to new versions of branchless. 
I'm trying to remember the sequence of events that led to this but it's been a while since I created those commits. I'm 100% sure they've been created or modified (e.g. moved) long after I branchless init'd the repo. I first created the repo probably in November, started using Branchless around December, and these commits were between 2 and 4 months old. 

As for your hide/gc/unhide theory, I think it's unlikely as you described but it's possible that they were affected by some sequence of git move then git undo or git move and git unhide. This is because I sometimes move old commits forward, try to address merge conflicts, then decide it's not worth it right now so abort. However, it seems strange that all 4 of my old commits disappeared at the same time. I guess if I managed to remove all the gc references through various actions and then a gc pass cleaned them up. 

Is there a way to get rid of them from this repo so they're not showing in the smartlog? They fail to hide because they can't be found.

**Comment by arxanas** [comment]
@AaronLieberman the simplest way to get rid of them is to attach branches to any commits you care about, then delete the event log database at `.git/branchless/db.sqlite3`. The principled solution is probably to add some `git branchless repair` command which will reconcile any mismatched commits/branches.
