### ISSUE TITLE
Garbage collected commits are not hideable

### ISSUE THREAD

**Issue by AaronLieberman** [arxanas/git-branchless#413]
### Description of the bug

I have several commits that have been hanging around for a month or two. I looked at my smartlog today and found they're now listed as `<garbage collected>`. I didn't expect them to be lost, filed that as https://github.com/arxanas/git-branchless/issues/412. Now that they're no longer useful, I want to hide them from the smartlog so I ran `git hide 2e6dd43`

### Expected behavior

Commit to be hidden.

### Actual behavior

`Commit not found: 2e6dd43`

### Version of `rustc`

rustc 1.61.0 (fe5b13d68 2022-05-18)

### Version of `git-branchless`

git-branchless 0.3.12

### Version of `git`

git version 2.36.1

**Comment by arxanas** [comment]
@AaronLieberman Thanks for reporting. You can try running the `git branchless repair` command in the latest `master` build to clean up these commits.

**Comment by AaronLieberman** [comment]
Worked great, thanks!
