### ISSUE TITLE
Explain in the README what makes git-branchless better

### ISSUE THREAD

**Issue by dfabulich** [arxanas/git-branchless#5]
The README says that `git-branchless` makes these things easier:

>   * Switching between work tasks.
>   * Separating minor cleanups/refactorings into their own commits, for ease of reviewability.
>   * Extensively rewriting local history before submitting code for review.
>   * Performing speculative work which may not be ultimately committed.
>   * Working on top of work that you or a collaborator produced, which is not yet checked in.
>   * Losing track of `git stash`es you made previously.

But it doesn't say _how_ it makes those tasks easier.

For example, I switch between work tasks today with [`git switch`](https://git-scm.com/docs/git-switch). How is `git-branchless` better than `git switch`? In the demo video, you demonstrate switching to a a commit as a detached HEAD instead of a branch. But I could have typed `git switch -c experiment1`. Was the whole advantage just "you don't have to type a name?" But then I have to use commit IDs as names. Seems about the same. What's the difference?

**Comment by arxanas** [comment]
A better tagline might be the following:

> `git-branchless` provides tooling to visualize and manipulate complex commit history.

I think that would make the scope of `git-branchless` clearer. It doesn't really help with your day-to-day workflow unless you're doing something like amending a parent of multiple commits, like in the demo at https://github.com/arxanas/git-branchless/issues/6#issuecomment-817018327. Only now that manipulating the commit history is easier do I regularly do it.

I'm not sure how to succinctly explain the idea that having to create a lot of branches gets in the way of creating and manipulating a complex commit history. I suppose the fact that it doesn't use branches is just a side effect! But according to https://github.com/arxanas/git-branchless/issues/4#issuecomment-812197426, "git branchless" was an intuitive description of the workflow.

It would also be worth explaining somewhere that there are two main camps of Git users:

* Users who believe that the commit history should be a readable log with self-contained changes, even if that requires aggressively editing it.
* Users who believe that the commit history should reflect the true development process, and shouldn't be changed if possible.

And `git-branchless` is primarily useful for the first kind of user.
