### ISSUE TITLE
`git reword --force-rewrite` on a public commit moves the remote-tracking branch.

### ISSUE THREAD

**Issue by ilyagr** [arxanas/git-branchless#516]
### Description of the bug

1. Be on a public commit (main branch) that's synced with the remote tracking branch (origin/main)..
2. Do `git reword --force-rewrite -m Something`.

### Expected behavior

The tip of the main branch moves to the reworded commit, but the origin/main branch stays where it was.

### Actual behavior

Both main and origin/main move to the reworded commit, which is a weird and confusing state for a git repository to be in, especially if you are the only person using it (as though somebody else force-pushed to the remote while you weren't looking) 

### Automated bug report

Same as https://github.com/arxanas/git-branchless/issues/515

**Comment by arxanas** [comment]
Hi @ilyagr, thanks for reporting. I agree that this is strange behavior; we should definitely only move local branches. I think this also causes issues if you try to do `git push --force-with-lease` later because your remote-tracking branch doesn't match the remote's branch.
