### ISSUE TITLE
git bisect leaves "should not appear" transactions in undo log

### ISSUE THREAD

**Issue by waych** [arxanas/git-branchless#57]
I did a bisect in my local dev tree yesterday, and noticed various transactions in `git undo` that have the following message: 

`This event should not appear. This is a (benign) bug -- please report it.`

I don't think bisect is a workflow that has been completely worked out for transactions yet?

Roughly looks like this (replacing commit ids and names with `...` throughout):

```
1. Empty event for ref BISECT_HEAD
   This event should not appear. This is a (benign) bug -- please report it.
```

at the start of the bisection, and later, after I did the bisection and screwed something up (resulting in a commit that was both good and bad) I did a `git bisect reset`, resulting in the following:

```
                1. Delete ref refs/bisect/bad at ...

                2. Delete ref refs/bisect/good-...

                3. Delete ref refs/bisect/good-...

                4. Delete ref refs/bisect/good-...

                5. Delete ref refs/bisect/good-...

                6. Delete ref refs/bisect/good-...

                7. Delete ref refs/bisect/good-...

                8. Delete ref refs/bisect/good-...

                9. Empty event for ref BISECT_HEAD
                   This event should not appear. This is a (benign) bug -- please report it.
```

followed by other transactions that looked like:

```
1. Empty event for ref refs/bisect/bad
    This event should not appear. This is a (benign) bug -- please report it
```

or 

```
1. Empty event for ref refs/bisect/good-...
    This event should not appear. This is a (benign) bug -- please report it.
```

one for each of the good / bad refs. Finally finishing with:

```
1. Empty event for ref BISECT_HEAD
    This event should not appear. This is a (benign) bug -- please report it.
```

**Comment by arxanas** [comment]
Thanks for reporting. I'll take a look later. I'm wondering if it needs to be added here:

https://github.com/arxanas/git-branchless/blob/646185fbaba290e37568d91a1777f4fd8aecc55c/src/core/eventlog.rs#L600

**Comment by arxanas** [comment]
It looks like stashes would also be affected:

> The latest stash you created is stored in `refs/stash`; older stashes are found in the reflog of this reference

Although ideally, under the branchless workflow, you wouldn't use stashes to begin with.

From a UX perspective, it probably makes sense to have different timelines for branches, bisects and stashes, but I'm not sure how we would represent that in the UI.

**Comment by arxanas** [comment]
I've closed this for now by changing the bug message to link to this page, and I've added an item to https://github.com/arxanas/git-branchless/issues/2 to track the issue of coming up with a better UI for undoing these kinds of events.

**Comment by arxanas** [comment]
Besides the issue of `git-bisect` operations appearing in the event log, it occurs to me that it would probably be useful if you could carry out a bisect operation across the event log itself. For example, you may want to figure out which of your rebase operations introduced a regression. In that case, you might want to bisect across a slice of the timeline including events that touched a given commit or branch.
