### ISSUE TITLE
Out of date Cargo.lock on v0.5.0 tag

### ISSUE THREAD

**Issue by singron** [arxanas/git-branchless#581]
### Description of the bug

The version of git-branchless is 0.4.0 in Cargo.lock. Cargo will refuse to compile the package if --frozen is given.

https://github.com/arxanas/git-branchless/blob/v0.5.0/Cargo.lock#L1082

### Expected behavior

It builds

### Actual behavior

```
$ cargo check --frozen
error: the lock file Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```

### Version of `rustc`

rustc 1.63.0

### Version of `git-branchless`

git-branchless 0.5.0

**Comment by arxanas** [comment]
Hi @singron, thanks for reporting. Can you let me know if the tag `v0.5.1` fixes the issue for you?

**Comment by singron** [comment]
Yep works. Thanks!
