### ISSUE TITLE
Divergent workflow should include instructions on how to un-detach confirmed work.

### ISSUE THREAD

**Issue by przemo-hemmersbach** [arxanas/git-branchless#660]
### Wiki page

https://github.com/arxanas/git-branchless/wiki/Workflow:-divergent-development

### Subcommand

---

### Description

Divergent Development gives instructions on detaching HEAD from current branch, thus it should also include instructions on how to consolidate those commits from detached HEAD to that branch.
In other words that page should end with git sl showing bottom commit as final commit with branch name marked on it.

One such way is to use `-` feature of git. Where `git merge -` will merge previous active commit onto current branch.
So: `git checkout {{branch on from which HEAD was detached}} && git merge -`` will nicely move branch pointer.

Or docs could reference some other source that will give proper instructions.

**Comment by arxanas** [comment]
Hi @przemo-hemmersbach, thanks for the feedback! I've added the section [Create a new branch](https://github.com/arxanas/git-branchless/wiki/Workflow:-Divergent-development#create-a-new-branch) to discuss some approaches. It also links to the discussion [Convenient way to move branch pointer around?](https://github.com/arxanas/git-branchless/discussions/402), which discusses similar operations. Feel free to update the Wiki page or add a comment to the Discussion.
