### ISSUE TITLE
Can't submit any branch while HEAD is detached

### ISSUE THREAD

**Issue by singron** [arxanas/git-branchless#665]
### Description of the bug

While HEAD is detached (e.g. checkout a commit that's not associated with a branch or checkout any commit with `--detach`), you cannot submit a branch (e.g. `git submit branchname`).

### Expected behavior

I expected it to push the branch.

### Actual behavior

The following error is printed and nothing is submitted.

```
$ git submit branchname
branchless: running command: git fetch origin
branchless: running command: git push --force-with-lease origin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Failed to push branches:
```

#### Software version

git-branchless 0.6.0

#### Operating system

macOS 12.5.1 (Darwin 21.6.0)

#### Command-line

```bash
/Users/eric/.local/nix-env/bin/git-branchless bug-report 
```

#### Environment variables

```bash
SHELL=/usr/local/bin/bash
EDITOR=vim
```

#### Git version

```
> git version 
git version 2.38.1
```

#### Hooks

<details>
<summary>Show 6 hooks</summary>

##### Hook `post-commit`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-commit "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-merge`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-merge "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-rewrite`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-rewrite "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-checkout`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-checkout "$@"

## END BRANCHLESS CONFIG
```
##### Hook `pre-auto-gc`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-pre-auto-gc "$@"

## END BRANCHLESS CONFIG
```
##### Hook `reference-transaction`

```
#!/bin/sh
## START BRANCHLESS CONFIG

# Avoid canceling the reference transaction in the case that `branchless` fails
# for whatever reason.
git branchless hook-reference-transaction "$@" || (
echo 'branchless: Failed to process reference transaction!'
echo 'branchless: Some events (e.g. branch updates) may have been lost.'
echo 'branchless: This is a bug. Please report it.'
)

## END BRANCHLESS CONFIG
```

</details>

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 98, transaction ID: 76 (message: submit)

1. `RefUpdateEvent { timestamp: 1669068212.126105, event_tx_id: EventTransactionId(76), ref_name: ReferenceName("refs/remotes/redacted-ref-0"), old_oid: 0000000000000000000000000000000000000000, new_oid: 0fa274c72ed5e0abc9f0cf2bce5e6d3a761cfc9b, message: None }`
```
:
O 67a8b48 3d (main) xxxxxx xxxxxxx x
|\
| o 79c7066 3d (redacted-ref-1) xxxxxx xxxxx
|\
| o 0fa274c 3d (redacted-ref-2) xxx xxxxxxxx
|
@ ba1dfbc 1m xxxxx xxxxxx
```
##### Event ID: 97, transaction ID: 74 (message: hook-post-checkout)

1. `RefUpdateEvent { timestamp: 1669068192.687775, event_tx_id: EventTransactionId(74), ref_name: ReferenceName("HEAD"), old_oid: 67a8b4850ba347d6cbe6480c5e272fac3f91077d, new_oid: ba1dfbcb5debee207886a4c6071f45e1e20e19cd, message: None }`
```
:
O 67a8b48 3d (main) xxxxxx xxxxxxx x
|\
| o 79c7066 3d (redacted-ref-1) xxxxxx xxxxx
|\
| o 0fa274c 3d (redacted-ref-2) xxx xxxxxxxx
|
@ ba1dfbc 1m xxxxx xxxxxx
```
##### Event ID: 96, transaction ID: 73 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1669068192.649753, event_tx_id: EventTransactionId(73), ref_name: ReferenceName("HEAD"), old_oid: 0000000000000000000000000000000000000000, new_oid: ba1dfbcb5debee207886a4c6071f45e1e20e19cd, message: None }`
```
:
O 67a8b48 3d (main) xxxxxx xxxxxxx x
|\
| o 79c7066 3d (redacted-ref-1) xxxxxx xxxxx
|\
| o 0fa274c 3d (redacted-ref-2) xxx xxxxxxxx
|
@ ba1dfbc 1m xxxxx xxxxxx
```
##### Event ID: 95, transaction ID: 72 (message: hook-post-checkout)

1. `RefUpdateEvent { timestamp: 1669068187.093464, event_tx_id: EventTransactionId(72), ref_name: ReferenceName("HEAD"), old_oid: 67a8b4850ba347d6cbe6480c5e272fac3f91077d, new_oid: 67a8b4850ba347d6cbe6480c5e272fac3f91077d, message: None }`
```
:
O 67a8b48 3d (main) xxxxxx xxxxxxx x
|\
| o 79c7066 3d (redacted-ref-1) xxxxxx xxxxx
|\
| o 0fa274c 3d (redacted-ref-2) xxx xxxxxxxx
|
@ ba1dfbc 1m xxxxx xxxxxx
```
##### Event ID: 94, transaction ID: 71 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1669068187.054871, event_tx_id: EventTransactionId(71), ref_name: ReferenceName("refs/heads/main"), old_oid: 0000000000000000000000000000000000000000, new_oid: 67a8b4850ba347d6cbe6480c5e272fac3f91077d, message: None }`
```
:
O 67a8b48 3d (main) xxxxxx xxxxxxx x
|\
| o 79c7066 3d (redacted-ref-1) xxxxxx xxxxx
|\
| o 0fa274c 3d (redacted-ref-2) xxx xxxxxxxx
|
@ ba1dfbc 1m xxxxx xxxxxx
```

</details>

**Comment by arxanas** [comment]
Hi @singron, thanks for reporting. I think the error message is misleading here. It's running `git push origin` with an empty set of branches, which, in Git, will push the current branch by default (which will then happen to fail if your `HEAD` is detached). This should only happen when the branch is up-to-date, though. Can you try https://github.com/arxanas/git-branchless/pull/670 and see if it resolves the issue for you? (See https://github.com/arxanas/git-branchless/wiki/Runbook#manual-testing for details on installing the PR version.)

**Comment by arxanas** [comment]
I merged https://github.com/arxanas/git-branchless/pull/670. Let me know if the issue still occurs.

**Comment by singron** [comment]
I just tested with the above PR, and the issue is fixed. Thanks!!
