### ISSUE TITLE
Commits created with `git am` aren't seen by git-branchless

### ISSUE THREAD

**Issue by mlcui-google** [arxanas/git-branchless#689]
### Description of the bug

Summary: Creating a commit with `git am` means that git-branchless "doesn't know about it" - it doesn't even show up in `git sl --hidden` unless it's pointed to by a branch, or it's explicitly hidden / unhidden.

<details>
<summary>
Terminal session showing issue
</summary>

```
$ git init
$ git commit --allow-empty -m "Initial commit"
[main (root-commit) 80c97ef] Initial commit

$ git branchless init
Created config file at [...]
Auto-detected your main branch as: main
If this is incorrect, run: git branchless init --main-branch <branch>
Installing hooks: post-commit, post-merge, post-rewrite, post-checkout, pre-auto-gc, reference-transaction
Successfully installed git-branchless.
To uninstall, run: git branchless init --uninstall

$ git sl
◆ 80c97ef 38s (ᐅ main) Initial commit

$ cat ../create-a-txt.patch 
From 482ce159aa9126df64dc159f3ccf6bade662d16d Mon Sep 17 00:00:00 2001
From: mlcui <mlcui@google.com>
Date: Mon, 5 Dec 2022 09:24:30 +1100
Subject: [PATCH] Create a.txt

---
 a.txt | 0
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a.txt

diff --git a/a.txt b/a.txt
new file mode 100644
index 0000000..e69de29
-- 


$ git am < ../create-a-txt.patch 
Applying: Create a.txt
branchless: processing 2 updates: branch main, ref HEAD

$ git sl
⋮
◆ cd31179 1s (ᐅ main) Create a.txt

$ # Oops, that shouldn't be on main!
$ git reset --hard HEAD^
branchless: processing 2 updates: branch main, ref HEAD
HEAD is now at 80c97ef Initial commit

$ git sl
◆ 80c97ef 1m (ᐅ main) Initial commit

$ # Where did that commit go?
$ git sl --hidden
◆ 80c97ef 1m (ᐅ main) Initial commit

$ git branchless bug-report
# Bug report attached below.

$ git unhide cd31179
Unhid commit: cd31179 Create a.txt
To hide this 1 commit, run: git undo

$ git branchless bug-report
# Bug report attached below (see "Events (after unhide)")

$ git sl
◆ 80c97ef 5m (ᐅ main) Initial commit
┃
◯ cd31179 4m Create a.txt

$ git hide cd31179
Hid commit: cd31179 Create a.txt
To unhide this 1 commit, run: git undo

$ git sl --hidden
◆ 80c97ef 6m (ᐅ main) Initial commit
┃
✕ cd31179 5m (manually hidden) Create a.tx
```

</details>

### Expected behavior

Commits created with `git am` work like any other commit.

### Actual behavior

Commits created with `git am` gets forgotten by git-branchless until an hide / unhide.

#### Software version

git-branchless 0.7.0-pre.1 (v0.3.6-nixos.0-655-gf698e09)

#### Operating system

Linux 5.19.11-1rodete1-amd64

#### Command-line

```bash
~/.cargo/bin/git-branchless bug-report 
```

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=nvim
```

#### Git version

```
> git version 
git version 2.39.0.rc0.267.gcb52ba06e7-goog
```

#### Hooks

<details>
<summary>Show 6 hooks</summary>

##### Hook `post-commit`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-commit "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-merge`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-merge "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-rewrite`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-rewrite "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-checkout`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-checkout "$@"

## END BRANCHLESS CONFIG
```
##### Hook `pre-auto-gc`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-pre-auto-gc "$@"

## END BRANCHLESS CONFIG
```
##### Hook `reference-transaction`

```
#!/bin/sh
## START BRANCHLESS CONFIG

# Avoid canceling the reference transaction in the case that `branchless` fails
# for whatever reason.
git branchless hook-reference-transaction "$@" || (
echo 'branchless: Failed to process reference transaction!'
echo 'branchless: Some events (e.g. branch updates) may have been lost.'
echo 'branchless: This is a bug. Please report it.'
)

## END BRANCHLESS CONFIG
```

</details>

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 3, transaction ID: 6 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1670193465.8203936, event_tx_id: EventTransactionId(6), ref_name: ReferenceName("HEAD"), old_oid: cd31179abfbf6a59539d03f757246edbac6f96ca, new_oid: 80c97ef01624e66e9d43244e1d79385cb8e0caaa, message: None }`
1. `RefUpdateEvent { timestamp: 1670193465.8203936, event_tx_id: EventTransactionId(6), ref_name: ReferenceName("refs/heads/main"), old_oid: cd31179abfbf6a59539d03f757246edbac6f96ca, new_oid: 80c97ef01624e66e9d43244e1d79385cb8e0caaa, message: None }`
```
@ 80c97ef 1m (> main) xxxxxxx xxxxxx
```
##### Event ID: 1, transaction ID: 3 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1670193448.2598515, event_tx_id: EventTransactionId(3), ref_name: ReferenceName("HEAD"), old_oid: 80c97ef01624e66e9d43244e1d79385cb8e0caaa, new_oid: cd31179abfbf6a59539d03f757246edbac6f96ca, message: None }`
1. `RefUpdateEvent { timestamp: 1670193448.2598515, event_tx_id: EventTransactionId(3), ref_name: ReferenceName("refs/heads/main"), old_oid: 80c97ef01624e66e9d43244e1d79385cb8e0caaa, new_oid: cd31179abfbf6a59539d03f757246edbac6f96ca, message: None }`
```
@ 80c97ef 1m (> main) xxxxxxx xxxxxx
```
There are no previous available events.
```
@ 80c97ef 1m (> main) xxxxxxx xxxxxx
```
There are no previous available events.
```
@ 80c97ef 1m (> main) xxxxxxx xxxxxx
```
There are no previous available events.
```
@ 80c97ef 1m (> main) xxxxxxx xxxxxx
```

</details>

#### Events (after unhide)

<details>
<summary>Show 5 events</summary>

##### Event ID: 5, transaction ID: 7 (message: unhide)

1. `UnobsoleteEvent { timestamp: 1670193582.7619789, event_tx_id: EventTransactionId(7), commit_oid: NonZeroOid(cd31179abfbf6a59539d03f757246edbac6f96ca) }`
```
@ 80c97ef 3m (> main) xxxxxxx xxxxxx
|
o cd31179 2m xxxxxx xxxxx
```
##### Event ID: 3, transaction ID: 6 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1670193465.8203936, event_tx_id: EventTransactionId(6), ref_name: ReferenceName("HEAD"), old_oid: cd31179abfbf6a59539d03f757246edbac6f96ca, new_oid: 80c97ef01624e66e9d43244e1d79385cb8e0caaa, message: None }`
1. `RefUpdateEvent { timestamp: 1670193465.8203936, event_tx_id: EventTransactionId(6), ref_name: ReferenceName("refs/heads/main"), old_oid: cd31179abfbf6a59539d03f757246edbac6f96ca, new_oid: 80c97ef01624e66e9d43244e1d79385cb8e0caaa, message: None }`
```
@ 80c97ef 3m (> main) xxxxxxx xxxxxx
|
o cd31179 2m xxxxxx xxxxx
```
##### Event ID: 1, transaction ID: 3 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1670193448.2598515, event_tx_id: EventTransactionId(3), ref_name: ReferenceName("HEAD"), old_oid: 80c97ef01624e66e9d43244e1d79385cb8e0caaa, new_oid: cd31179abfbf6a59539d03f757246edbac6f96ca, message: None }`
1. `RefUpdateEvent { timestamp: 1670193448.2598515, event_tx_id: EventTransactionId(3), ref_name: ReferenceName("refs/heads/main"), old_oid: 80c97ef01624e66e9d43244e1d79385cb8e0caaa, new_oid: cd31179abfbf6a59539d03f757246edbac6f96ca, message: None }`
```
@ 80c97ef 3m (> main) xxxxxxx xxxxxx
|
o cd31179 2m xxxxxx xxxxx
```
There are no previous available events.
```
@ 80c97ef 3m (> main) xxxxxxx xxxxxx
|
o cd31179 2m xxxxxx xxxxx
```
There are no previous available events.
```
@ 80c97ef 3m (> main) xxxxxxx xxxxxx
|
o cd31179 2m xxxxxx xxxxx
```

</details>

### Version of `git-branchless`

5c13964b26dca5ed70540b60e5ac342d8d4ff7aa

**Comment by arxanas** [comment]
Thanks for reporting. It looks like `git am` doesn't invoke the `post-commit` hook, which is what we use to mark commits live in git-branchless. It seems like it should be possible to install a `post-applypatch` hook to fix this.
