### ISSUE TITLE
Conflict with other git test tools during unit tests

### ISSUE THREAD

**Issue by bodograumann** [arxanas/git-branchless#690]
### Description of the bug

I am trying to install git branchless on arch via AUR, which is running the build and unit tests locally.
Some of these unittests, because I have another tool installed, which provides the `git test` subcommand.
Cf. https://aur.archlinux.org/packages/git-test

This is especially frustrating as the build takes a while.

### Expected behavior

Successfully run the unittests regardless.

### Actual behavior

Relies on the fact that `git test` refers to the git branchless tool.

### Version of `git-branchless`

0.6.0

### Version of `git`

2.38.1

**Comment by arxanas** [comment]
Hi @bodograumann, thanks for reporting. Unfortunately, as per https://github.com/arxanas/git-branchless/discussions/678, it's difficult to prevent the host's Git configuration from leaking into the tests.

To fix the issue for `git test` in particular, I opened https://github.com/arxanas/git-branchless/pull/696. Could you try it out and see if it resolves the testing on your system?

By the way, git-branchless's `git test` is meant to supersede Spotify's `git-test`. If there are some workflows supported by the latter but not the former, I would be interested to know what they are, to bring git-branchless's version up to parity.

**Comment by mlcui-google** [comment]
The `git` commands in tests shouldn't be using any other configuration (system or global), as `GIT_CONFIG_NOSYSTEM` is set (so system config isn't used, contrary to what `git config --system --all` outputs) and `HOME` isn't set (so [the global config doesn't exist](https://github.com/arxanas/git-branchless/blob/928c374b0e59bc82fcabf9c1f27e29f1adb3b8fa/git-branchless/tests/test_git.rs#L22)): https://github.com/arxanas/git-branchless/blob/928c374b0e59bc82fcabf9c1f27e29f1adb3b8fa/git-branchless-lib/src/testing.rs#L168-L176

https://github.com/arxanas/git-branchless/discussions/678 is specifically referring to `git-branchless` accessing config variables, as it goes through `libgit2` which doesn't respect `GIT_CONFIG_NOSYSTEM`. Calls to the git binary shouldn't be affected.

I don't know why `git test` is leaking into tests, though, as I assume it should be set as an alias in the local config...

**Comment by mlcui-google** [comment]
Doing some more investigation:

- Local aliases do not override `git-<name>` binaries in `$PATH`. See https://stackoverflow.com/q/3538774.
- `$PATH` in tests could contain other binaries, as the parent directory of where `bash` lives is in the test `$PATH`:
  https://github.com/arxanas/git-branchless/blob/928c374b0e59bc82fcabf9c1f27e29f1adb3b8fa/git-branchless-lib/src/testing.rs#L140-L147
- `git-test` in the AUR [is installed to `/usr/bin`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=git-test#n17), [the same place where `bash` is installed on Arch](https://archlinux.org/packages/core/x86_64/bash/).

So… any `git-<name>` binaries in `bash_path` named the same as a `git-branchless` alias will cause test issues. In theory, we should remove `bash_path` from `$PATH` to resolve this... but then `git-branchless` can't invoke `bash`. Not sure sure what the best way forward is.

**Comment by arxanas** [comment]
@mlcui-google Thanks for the investigation. I suppose the most appropriate thing is to create a new temporary directory and add the symlinks to executables we want in our `$PATH` there?

**Comment by mlcui-google** [comment]
Good idea - that should work!

**Comment by arxanas** [comment]
@bodograumann I committed https://github.com/arxanas/git-branchless/pull/696 — does that fix the tests for you?

**Comment by bodograumann** [comment]
Great @arxanas, those tests seem to work now. Do you want to keep this issue open for the solution with a temporary directory?

Fyi, there is one test case that fails now, but it seems unrelated. Maybe it happens because I still have `master` as my local default branch name instead of `main`?
```
failures:

---- test_sync_no_delete_main_branch stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: sync_no_delete_main_branch
Source: git-branchless/tests/test_sync.rs:364
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: stderr
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    3     3 │ branchless: processing 1 rewritten commit␊
    4     4 │ branchless: processing 2 updates: branch master, branch should-be-deleted␊
    5     5 │ branchless: creating working copy snapshot␊
    6     6 │ branchless: running command: <git-executable> checkout master␊
    7       │-Switched to branch 'master'␊
          7 │+␊
    8     8 │ branchless: processing checkout␊
    9     9 │ :␊
   10    10 │ @ 96d1c37 (> master) create test2.txt␊
   11       │-Successfully rebased and updated detached HEAD.
         11 │+Successfully rebased and updated detached HEAD.␊
```

**Comment by arxanas** [comment]
@bodograumann That test is flaky and I have no idea why/how it would be. It sometimes prints the "Switched to branch" message and sometimes doesn't. You can re-run/ignore that particular failure.

I'll close this for now. It would be nice to have the executables in a dedicated directory, but it doesn't seem like it's blocking anyone for now.
