### ISSUE TITLE
`git amend` on a checked out branch detaches HEAD after amend

### ISSUE THREAD

**Issue by mlcui-google** [arxanas/git-branchless#706]
### Description of the bug

See command log below:

<details>
<summary>
Command log
</summary>

```
$ git init
Initialized empty Git repository in ~/git/branchless-testing/amend-switch-branch/.git/

$ git commit --allow-empty -m "Initial commit"
[main (root-commit) 6748bca] Initial commit

$ git branchless init
Created config file at ~/git/branchless-testing/amend-switch-branch/.git/branchless/config
Auto-detected your main branch as: main
If this is incorrect, run: git branchless init --main-branch <branch>
Installing hooks: post-commit, post-merge, post-rewrite, post-checkout, pre-auto-gc, reference-transaction
Successfully installed git-branchless.
To uninstall, run: git branchless init --uninstall

$ git sl
◆ 6748bca 2m (ᐅ main) Initial commit

$ echo "Hello, world!" > a.txt && git add a.txt

$ git sw -c feature
branchless: creating working copy snapshot
branchless: running command: git checkout -b feature
branchless: processing 1 update: branch feature
Switched to a new branch 'feature'
branchless: processing checkout
◆ 6748bca 3m (main, ᐅ feature) Initial commit

$ git commit -m "a: Hello, world!"
branchless: processing 2 updates: branch feature, ref HEAD
branchless: processed commit: 6c08b62 a: Hello, world!
[feature 6c08b62] a: Hello, world!
 1 file changed, 1 insertion(+)
 create mode 100644 a.txt

$ git sl
◇ 6748bca 3m (main) Initial commit
┃
● 6c08b62 1s (ᐅ feature) a: Hello, world!

$ sed 's/,//' a.txt > a.txt

$ git status
On branch feature
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   a.txt

no changes added to commit (use "git add" and/or "git commit -a")

$ git sl
◇ 6748bca 4m (main) Initial commit
┃
● 6c08b62 1m (ᐅ feature) a: Hello, world!

$ git amend
branchless: creating working copy snapshot
branchless: running command: git reset 772e48c2d186aa12cca4f598d0d53cf706835166
branchless: processing 2 updates: branch feature, ref HEAD
branchless: running command: git checkout 772e48c2d186aa12cca4f598d0d53cf706835166
branchless: processing 1 update: ref HEAD
HEAD is now at 772e48c a: Hello, world!
branchless: processing checkout
Attempting rebase in-memory...
[1/1] Committed as: 772e48c a: Hello, world!
branchless: processing 1 rewritten commit
In-memory rebase succeeded.
Amended with 1 uncommitted change.

$ git status
HEAD detached at 772e48c
nothing to commit, working tree clean

$ git sl
◇ 6748bca 4m (main) Initial commit
┃
● 772e48c 5s (feature) a: Hello, world!
```

</details>

### Expected behavior

If a branch is checked out, running `git amend` will not detach HEAD and the currently checked out branch does not change.

### Actual behavior

If a branch is checked out, running `git amend` detaches HEAD.

#### Software version

git-branchless 0.7.0-pre.1 (v0.3.6-nixos.0-675-ga403ed4-modified)

#### Operating system

Linux 5.19.11-1rodete1-amd64

#### Command-line

```bash
~/.cargo/bin/git-branchless bug-report 
```

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=nvim
```

#### Git version

```
> git version 
git version 2.39.0.rc1.256.g54fd8350bd-goog
```

#### Hooks

<details>
<summary>Show 6 hooks</summary>

##### Hook `post-commit`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-commit "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-merge`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-merge "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-rewrite`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-rewrite "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-checkout`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-checkout "$@"

## END BRANCHLESS CONFIG
```
##### Hook `pre-auto-gc`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-pre-auto-gc "$@"

## END BRANCHLESS CONFIG
```
##### Hook `reference-transaction`

```
#!/bin/sh
## START BRANCHLESS CONFIG

# Avoid canceling the reference transaction in the case that `branchless` fails
# for whatever reason.
git branchless hook-reference-transaction "$@" || (
echo 'branchless: Failed to process reference transaction!'
echo 'branchless: Some events (e.g. branch updates) may have been lost.'
echo 'branchless: This is a bug. Please report it.'
)

## END BRANCHLESS CONFIG
```

</details>

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 7, transaction ID: 4 (message: amend)

1. `WorkingCopySnapshot { timestamp: 1670893403.3184912, event_tx_id: EventTransactionId(4), head_oid: 6c08b6263b95601a57f5c90ee7314f9ac019db56, commit_oid: NonZeroOid(d6a7243670f5a7d5f39c4a415e22f2c048ab8b7a), ref_name: Some(ReferenceName("refs/heads/redacted-ref-0")) }`
1. `WorkingCopySnapshot { timestamp: 1670893403.3769457, event_tx_id: EventTransactionId(4), head_oid: 6c08b6263b95601a57f5c90ee7314f9ac019db56, commit_oid: NonZeroOid(d6a7243670f5a7d5f39c4a415e22f2c048ab8b7a), ref_name: Some(ReferenceName("refs/heads/redacted-ref-0")) }`
1. `RefUpdateEvent { timestamp: 1670893403.4533484, event_tx_id: EventTransactionId(4), ref_name: ReferenceName("HEAD"), old_oid: 6c08b6263b95601a57f5c90ee7314f9ac019db56, new_oid: 772e48c2d186aa12cca4f598d0d53cf706835166, message: None }`
1. `RefUpdateEvent { timestamp: 1670893403.4533484, event_tx_id: EventTransactionId(4), ref_name: ReferenceName("refs/heads/redacted-ref-0"), old_oid: 6c08b6263b95601a57f5c90ee7314f9ac019db56, new_oid: 772e48c2d186aa12cca4f598d0d53cf706835166, message: None }`
1. `RefUpdateEvent { timestamp: 1670893403.505393, event_tx_id: EventTransactionId(4), ref_name: ReferenceName("HEAD"), old_oid: 0000000000000000000000000000000000000000, new_oid: 772e48c2d186aa12cca4f598d0d53cf706835166, message: None }`
1. `RefUpdateEvent { timestamp: 1670893403.5357332, event_tx_id: EventTransactionId(4), ref_name: ReferenceName("HEAD"), old_oid: 772e48c2d186aa12cca4f598d0d53cf706835166, new_oid: 772e48c2d186aa12cca4f598d0d53cf706835166, message: None }`
1. `RewriteEvent { timestamp: 1670893403.5863533, event_tx_id: EventTransactionId(4), old_commit_oid: 6c08b6263b95601a57f5c90ee7314f9ac019db56, new_commit_oid: 772e48c2d186aa12cca4f598d0d53cf706835166 }`
```
O 6748bca 6m (main) xxxxxxx xxxxxx
|
@ 772e48c 2m (redacted-ref-0) xx xxxxxx xxxxxx
```
##### Event ID: 6, transaction ID: 3 (message: post-commit)

1. `CommitEvent { timestamp: 1670893323.0, event_tx_id: EventTransactionId(3), commit_oid: NonZeroOid(6c08b6263b95601a57f5c90ee7314f9ac019db56) }`
```
O 6748bca 6m (main) xxxxxxx xxxxxx
|
@ 772e48c 2m (redacted-ref-0) xx xxxxxx xxxxxx
```
##### Event ID: 4, transaction ID: 2 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1670893323.7142448, event_tx_id: EventTransactionId(2), ref_name: ReferenceName("HEAD"), old_oid: 6748bca6442f02888a5d4fff6505790d2dcaf678, new_oid: 6c08b6263b95601a57f5c90ee7314f9ac019db56, message: None }`
1. `RefUpdateEvent { timestamp: 1670893323.7142448, event_tx_id: EventTransactionId(2), ref_name: ReferenceName("refs/heads/redacted-ref-0"), old_oid: 6748bca6442f02888a5d4fff6505790d2dcaf678, new_oid: 6c08b6263b95601a57f5c90ee7314f9ac019db56, message: None }`
```
O 6748bca 6m (main) xxxxxxx xxxxxx
|
@ 772e48c 2m (redacted-ref-0) xx xxxxxx xxxxxx
```
##### Event ID: 1, transaction ID: 1 (message: checkout)

1. `WorkingCopySnapshot { timestamp: 1670893312.1329336, event_tx_id: EventTransactionId(1), head_oid: 6748bca6442f02888a5d4fff6505790d2dcaf678, commit_oid: NonZeroOid(ea0a18207285495fcde9a01abe7a7ca45d21c751), ref_name: Some(ReferenceName("refs/heads/main")) }`
1. `RefUpdateEvent { timestamp: 1670893312.1846502, event_tx_id: EventTransactionId(1), ref_name: ReferenceName("refs/heads/redacted-ref-0"), old_oid: 0000000000000000000000000000000000000000, new_oid: 6748bca6442f02888a5d4fff6505790d2dcaf678, message: None }`
1. `RefUpdateEvent { timestamp: 1670893312.208986, event_tx_id: EventTransactionId(1), ref_name: ReferenceName("HEAD"), old_oid: 6748bca6442f02888a5d4fff6505790d2dcaf678, new_oid: 6748bca6442f02888a5d4fff6505790d2dcaf678, message: None }`
```
O 6748bca 6m (main) xxxxxxx xxxxxx
|
@ 772e48c 2m (redacted-ref-0) xx xxxxxx xxxxxx
```
There are no previous available events.
```
O 6748bca 6m (main) xxxxxxx xxxxxx
|
@ 772e48c 2m (redacted-ref-0) xx xxxxxx xxxxxx
```

</details>

### Version of `git-branchless`

cad2e1a

**Comment by ocharles** [comment]
This seems to be new, as I'm suddenly seeing this and am a frequent `git amend` user

**Comment by arxanas** [comment]
Hi @mlcui-google  and @ocharles, thanks for reporting and confirming. I was recently refactoring `git amend`, and this looks like a regression that appeared as a result. I opened https://github.com/arxanas/git-branchless/pull/707 to address this.
