### ISSUE TITLE
Failed to move w/ "Command not found" message after rebase -i

### ISSUE THREAD

**Issue by AaronLieberman** [arxanas/git-branchless#717]
### Description of the bug

git move -s 72510b3 -d 1908297

I just had done a `git rebase -i` a minute ago to reword a commit. (I didn't use git reword because that's not working for me, I'll file a different bug for that.) It didn't auto restack after the rebase so I tried restacking it myself. `git restack` didn't work so I attempted a move. I think all three commands failed for this same reason. 

Running on Windows in a PowerShell terminal.

### Expected behavior

Expected my commit to move cleanly.

### Actual behavior

`post-rewrite: line 4: git: command not found`

### Version of `rustc`

rustc 1.61.0 (fe5b13d68 2022-05-18)

#### Software version

git-branchless 0.6.0

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
git-branchless bug-report 
```

#### Environment variables

```bash
SHELL=<not set>
EDITOR=<not set>
```

#### Git version

```
> git version 
git version 2.35.1.windows.2
```

#### Hooks

<details>
<summary>Show 6 hooks</summary>

##### Hook `post-commit`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-commit "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-merge`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-merge "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-rewrite`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-rewrite "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-checkout`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-checkout "$@"
## END BRANCHLESS CONFIG
```
##### Hook `pre-auto-gc`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-pre-auto-gc "$@"
## END BRANCHLESS CONFIG
```
##### Hook `reference-transaction`

```
#!/bin/sh
## START BRANCHLESS CONFIG

# Avoid canceling the reference transaction in the case that `branchless` fails
# for whatever reason.
git branchless hook-reference-transaction "$@" || (
echo 'branchless: Failed to process reference transaction!'
echo 'branchless: Some events (e.g. branch updates) may have been lost.'
echo 'branchless: This is a bug. Please report it.'
)
## END BRANCHLESS CONFIG
```

</details>

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 306, transaction ID: 439 (message: rebase)

1. `RefUpdateEvent { timestamp: 1672339889.2413557, event_tx_id: EventTransactionId(439), ref_name: ReferenceName("HEAD"), old_oid: 0000000000000000000000000000000000000000, new_oid: 5349ae9e1c77654236caf906c13b796d38a16e37, message: None }`
1. `RefUpdateEvent { timestamp: 1672339889.4591146, event_tx_id: EventTransactionId(439), ref_name: ReferenceName("HEAD"), old_oid: 5dc88f044377d1a8b667231b17ec1d44540346cc, new_oid: 5349ae9e1c77654236caf906c13b796d38a16e37, message: None }`
1. `RefUpdateEvent { timestamp: 1672339891.0299535, event_tx_id: EventTransactionId(439), ref_name: ReferenceName("HEAD"), old_oid: 5349ae9e1c77654236caf906c13b796d38a16e37, new_oid: 539a2bfb2640843081e48caeeac45ab4df38b28a, message: None }`
1. `RefUpdateEvent { timestamp: 1672339903.106767, event_tx_id: EventTransactionId(439), ref_name: ReferenceName("HEAD"), old_oid: 539a2bfb2640843081e48caeeac45ab4df38b28a, new_oid: 1310cc387319a2b3670005fa7c9340247947d6f6, message: None }`
1. `CommitEvent { timestamp: 1672339891.0, event_tx_id: EventTransactionId(439), commit_oid: NonZeroOid(1310cc387319a2b3670005fa7c9340247947d6f6) }`
1. `RewriteEvent { timestamp: 1672339903.6040623, event_tx_id: EventTransactionId(439), old_commit_oid: 539a2bfb2640843081e48caeeac45ab4df38b28a, new_commit_oid: 1310cc387319a2b3670005fa7c9340247947d6f6 }`
1. `RefUpdateEvent { timestamp: 1672339905.3597784, event_tx_id: EventTransactionId(439), ref_name: ReferenceName("HEAD"), old_oid: 1310cc387319a2b3670005fa7c9340247947d6f6, new_oid: 1908297253b926fa78c012b7386009ece26d454e, message: None }`
1. `CommitEvent { timestamp: 1672339905.0, event_tx_id: EventTransactionId(439), commit_oid: NonZeroOid(1908297253b926fa78c012b7386009ece26d454e) }`
1. `RefUpdateEvent { timestamp: 1672339907.838344, event_tx_id: EventTransactionId(439), ref_name: ReferenceName("HEAD"), old_oid: 1908297253b926fa78c012b7386009ece26d454e, new_oid: 1ad62d3675d83568af68d80ed1ab56f4a0e7ff5a, message: None }`
1. `CommitEvent { timestamp: 1672339907.0, event_tx_id: EventTransactionId(439), commit_oid: NonZeroOid(1ad62d3675d83568af68d80ed1ab56f4a0e7ff5a) }`
1. `RewriteEvent { timestamp: 1672339908.9883745, event_tx_id: EventTransactionId(439), old_commit_oid: 539a2bfb2640843081e48caeeac45ab4df38b28a, new_commit_oid: 1310cc387319a2b3670005fa7c9340247947d6f6 }`
1. `RewriteEvent { timestamp: 1672339908.9883745, event_tx_id: EventTransactionId(439), old_commit_oid: 380f2d4a08d320c1df0e5ea413d642ab1efb707c, new_commit_oid: 1908297253b926fa78c012b7386009ece26d454e }`
1. `RewriteEvent { timestamp: 1672339908.9883745, event_tx_id: EventTransactionId(439), old_commit_oid: 5dc88f044377d1a8b667231b17ec1d44540346cc, new_commit_oid: 1ad62d3675d83568af68d80ed1ab56f4a0e7ff5a }`
```
:
O 5077521 26d xxxxxxxx
|\
: o 9fe68b6 25d (redacted-ref-0) xxxx xxxxxxx xxxx
:
O 6ec7825 2d xxxxxx xxxx xxxx xxxxxxx xx xxx xxxxxxxxxxxxxxxxx xxxxx xxxxxxx xxxxxxx xxxxx
|\
: o eb83350 2d xxxxxx xx xxxxxxx xxxxxxxxx xxx xxxxxxxxxxxx
:
O 5dc59ca 1d (main) xxxxxx xxxx xxxxxxxxx xxxxxxxx xxxxx xxxxxxxxx xxxxxxxx xxxxxx xxx xxxxxxx
|
o 5349ae9 1d xxxxxx xxxxxxxxxxxx xxxxx xxxxxxx xxxx xxxxxxxx xxxx
|\
| x 539a2bf 23h (rewritten as 1310cc38) xxxxxxxxxxxx
| |
| x 380f2d4 15h (rewritten as 19082972) xxxxxxx xxx xxxxxx xxxx xxxxx
| |
| o 72510b3 15h xxxxxxxxx xxxxxx xxxxxxxx
|
o 1310cc3 3m xxxxxxxxxxxx xxxxxxxxx xxxxxx
|
o 1908297 3m xxxxxxx xxx xxxxxx xxxx xxxxx
|
@ 1ad62d3 2m xxxxxx xxxx xx xxxxxxxxx
```
##### Event ID: 303, transaction ID: 438 (message: amend)

1. `WorkingCopySnapshot { timestamp: 1672339787.7514672, event_tx_id: EventTransactionId(438), head_oid: ff860efd1a2da008e12c5035141c857065631fb4, commit_oid: NonZeroOid(d42dfe09561617495b9609735e5ed545f2b4a1d5), ref_name: None }`
1. `RewriteEvent { timestamp: 1672339787.7514672, event_tx_id: EventTransactionId(438), old_commit_oid: ff860efd1a2da008e12c5035141c857065631fb4, new_commit_oid: 5dc88f044377d1a8b667231b17ec1d44540346cc }`
1. `RefUpdateEvent { timestamp: 1672339788.8756182, event_tx_id: EventTransactionId(438), ref_name: ReferenceName("HEAD"), old_oid: 5dc88f044377d1a8b667231b17ec1d44540346cc, new_oid: 5dc88f044377d1a8b667231b17ec1d44540346cc, message: None }`
```
:
O 5077521 26d xxxxxxxx
|\
: o 9fe68b6 25d (redacted-ref-0) xxxx xxxxxxx xxxx
:
O 6ec7825 2d xxxxxx xxxx xxxx xxxxxxx xx xxx xxxxxxxxxxxxxxxxx xxxxx xxxxxxx xxxxxxx xxxxx
|\
: o eb83350 2d xxxxxx xx xxxxxxx xxxxxxxxx xxx xxxxxxxxxxxx
:
O 5dc59ca 1d (main) xxxxxx xxxx xxxxxxxxx xxxxxxxx xxxxx xxxxxxxxx xxxxxxxx xxxxxx xxx xxxxxxx
|
o 5349ae9 1d xxxxxx xxxxxxxxxxxx xxxxx xxxxxxx xxxx xxxxxxxx xxxx
|\
| x 539a2bf 23h xxxxxxxxxxxx
| |
| x 380f2d4 15h xxxxxxx xxx xxxxxx xxxx xxxxx
| |
| o 72510b3 15h xxxxxxxxx xxxxxx xxxxxxxx
|
o 1310cc3 3m xxxxxxxxxxxx xxxxxxxxx xxxxxx
|
o 1908297 3m xxxxxxx xxx xxxxxx xxxx xxxxx
|
@ 1ad62d3 2m xxxxxx xxxx xx xxxxxxxxx
```
##### Event ID: 301, transaction ID: 437 (message: commit)

1. `RefUpdateEvent { timestamp: 1672339764.2901428, event_tx_id: EventTransactionId(437), ref_name: ReferenceName("HEAD"), old_oid: 380f2d4a08d320c1df0e5ea413d642ab1efb707c, new_oid: ff860efd1a2da008e12c5035141c857065631fb4, message: None }`
1. `CommitEvent { timestamp: 1672339763.0, event_tx_id: EventTransactionId(437), commit_oid: NonZeroOid(ff860efd1a2da008e12c5035141c857065631fb4) }`
```
:
O 5077521 26d xxxxxxxx
|\
: o 9fe68b6 25d (redacted-ref-0) xxxx xxxxxxx xxxx
:
O 6ec7825 2d xxxxxx xxxx xxxx xxxxxxx xx xxx xxxxxxxxxxxxxxxxx xxxxx xxxxxxx xxxxxxx xxxxx
|\
: o eb83350 2d xxxxxx xx xxxxxxx xxxxxxxxx xxx xxxxxxxxxxxx
:
O 5dc59ca 1d (main) xxxxxx xxxx xxxxxxxxx xxxxxxxx xxxxx xxxxxxxxx xxxxxxxx xxxxxx xxx xxxxxxx
|
o 5349ae9 1d xxxxxx xxxxxxxxxxxx xxxxx xxxxxxx xxxx xxxxxxxx xxxx
|\
| x 539a2bf 23h xxxxxxxxxxxx
| |
| x 380f2d4 15h xxxxxxx xxx xxxxxx xxxx xxxxx
| |
| o 72510b3 15h xxxxxxxxx xxxxxx xxxxxxxx
|
o 1310cc3 3m xxxxxxxxxxxx xxxxxxxxx xxxxxx
|
o 1908297 3m xxxxxxx xxx xxxxxx xxxx xxxxx
|
@ 1ad62d3 2m xxxxxx xxxx xx xxxxxxxxx
```
##### Event ID: 295, transaction ID: 430 (message: rebase)

1. `RefUpdateEvent { timestamp: 1672283213.5915782, event_tx_id: EventTransactionId(430), ref_name: ReferenceName("HEAD"), old_oid: 380f2d4a08d320c1df0e5ea413d642ab1efb707c, new_oid: 72510b3be939c2f2378cb0e68697156fc6238959, message: None }`
1. `CommitEvent { timestamp: 1672283210.0, event_tx_id: EventTransactionId(430), commit_oid: NonZeroOid(72510b3be939c2f2378cb0e68697156fc6238959) }`
1. `RewriteEvent { timestamp: 1672283215.3240778, event_tx_id: EventTransactionId(430), old_commit_oid: 84bbf3ed8d0975c13eb3fb03e988102110916874, new_commit_oid: 72510b3be939c2f2378cb0e68697156fc6238959 }`
1. `WorkingCopySnapshot { timestamp: 1672283215.5736508, event_tx_id: EventTransactionId(430), head_oid: 72510b3be939c2f2378cb0e68697156fc6238959, commit_oid: NonZeroOid(e8f79a7ebac99aeb15b4e88fcb7ac0c2f5cff0e0), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1672283215.8707058, event_tx_id: EventTransactionId(430), ref_name: ReferenceName("HEAD"), old_oid: 0000000000000000000000000000000000000000, new_oid: 380f2d4a08d320c1df0e5ea413d642ab1efb707c, message: None }`
1. `RefUpdateEvent { timestamp: 1672283216.0273118, event_tx_id: EventTransactionId(430), ref_name: ReferenceName("HEAD"), old_oid: 72510b3be939c2f2378cb0e68697156fc6238959, new_oid: 380f2d4a08d320c1df0e5ea413d642ab1efb707c, message: None }`
```
:
O 5077521 26d xxxxxxxx
|\
: o 9fe68b6 25d (redacted-ref-0) xxxx xxxxxxx xxxx
:
O 6ec7825 2d xxxxxx xxxx xxxx xxxxxxx xx xxx xxxxxxxxxxxxxxxxx xxxxx xxxxxxx xxxxxxx xxxxx
|\
: o eb83350 2d xxxxxx xx xxxxxxx xxxxxxxxx xxx xxxxxxxxxxxx
:
O 5dc59ca 1d (main) xxxxxx xxxx xxxxxxxxx xxxxxxxx xxxxx xxxxxxxxx xxxxxxxx xxxxxx xxx xxxxxxx
|
o 5349ae9 1d xxxxxx xxxxxxxxxxxx xxxxx xxxxxxx xxxx xxxxxxxx xxxx
|\
| x 539a2bf 23h xxxxxxxxxxxx
| |
| x 380f2d4 15h xxxxxxx xxx xxxxxx xxxx xxxxx
| |
| o 72510b3 15h xxxxxxxxx xxxxxx xxxxxxxx
|
o 1310cc3 3m xxxxxxxxxxxx xxxxxxxxx xxxxxx
|
o 1908297 3m xxxxxxx xxx xxxxxx xxxx xxxxx
|
@ 1ad62d3 2m xxxxxx xxxx xx xxxxxxxxx
```
##### Event ID: 294, transaction ID: 428 (message: restack)

1. `RefUpdateEvent { timestamp: 1672283180.4215088, event_tx_id: EventTransactionId(428), ref_name: ReferenceName("HEAD"), old_oid: 0000000000000000000000000000000000000000, new_oid: 380f2d4a08d320c1df0e5ea413d642ab1efb707c, message: None }`
```
:
O 5077521 26d xxxxxxxx
|\
: o 9fe68b6 25d (redacted-ref-0) xxxx xxxxxxx xxxx
:
O 6ec7825 2d xxxxxx xxxx xxxx xxxxxxx xx xxx xxxxxxxxxxxxxxxxx xxxxx xxxxxxx xxxxxxx xxxxx
|\
: o eb83350 2d xxxxxx xx xxxxxxx xxxxxxxxx xxx xxxxxxxxxxxx
:
O 5dc59ca 1d (main) xxxxxx xxxx xxxxxxxxx xxxxxxxx xxxxx xxxxxxxxx xxxxxxxx xxxxxx xxx xxxxxxx
|
o 5349ae9 1d xxxxxx xxxxxxxxxxxx xxxxx xxxxxxx xxxx xxxxxxxx xxxx
|\
| x 539a2bf 23h xxxxxxxxxxxx
| |
| x 380f2d4 15h xxxxxxx xxx xxxxxx xxxx xxxxx
| |
| o 72510b3 15h xxxxxxxxx xxxxxx xxxxxxxx
|
o 1310cc3 3m xxxxxxxxxxxx xxxxxxxxx xxxxxx
|
o 1908297 3m xxxxxxx xxx xxxxxx xxxx xxxxx
|
@ 1ad62d3 2m xxxxxx xxxx xx xxxxxxxxx
```

</details>

### Version of `git-branchless`

git-branchless 0.6.0

### Version of `git`

git version 2.35.1.windows.2

**Comment by arxanas** [comment]
Does it work if you update the hook to invoke `git.exe` instead of `git`? It will be difficult for me to confirm a fix myself since I don't have a Windows machine.

We have Windows CI, but it's passing, and I'm not sure what kind of setup it is. What shell are you using? Perhaps it works in Powershell but not cmd?

**Comment by AaronLieberman** [comment]
git.exe didn't work but I replaced it with `C:/Users/aaron/.cargo/bin/git-branchless.exe` and that did the trick. :|

**Comment by arxanas** [comment]
Should we merge this issue into #370?

**Comment by AaronLieberman** [comment]
> Should we merge this issue into #370?

Lol, I had forgotten that I had even filed that! Sure, sounds like the same issue.
