### ISSUE TITLE
Install hooks into core.hooksPath instead of $GIT_DIR/hooks

### ISSUE THREAD

**Issue by slymon99** [arxanas/git-branchless#719]
### Description of the bug

If I have a custom hooks path, git-branchless will still install into $GIT_DIR/hooks which causes it to silently fail in a lot of ways

### Expected behavior

installs into hooksPath

### Actual behavior

installs into $GIT_DIR/hooks

**Comment by slymon99** [comment]
this was so confusing to try to figure out why nothing was working 😢

**Comment by arxanas** [comment]
@slymon99 did you mean to close this issue? If not, reopen it.

**Comment by slymon99** [comment]
This happens due to my company dynamically changing the hookspath based on the remote url. I wanted to look into it tomorrow and flesh out this issue more fully - it may be our fault.
