### ISSUE TITLE
Git branchless doesn't detect dynamically set hooks path

### ISSUE THREAD

**Issue by slymon99** [arxanas/git-branchless#720]
### Description of the bug

My company dynamically sets some configuration for the company repos by having uses add this to their ~/.gitconfig

```
[includeIf "hasconfig:remote.*.url:git@github.com:company/**"]
        path = ~/work/company/gitconfigcompany
```

this gitconfigcompany file contains

```
[core]
hooksPath = ~/work/company/hooks
```
where we install custom hooks.

Branchless will not detect this hooks path, and will still install in $GIT_DIR/hooks. But Git will detect this hooks path, and use ~/work/company/hooks, meaning git-branchless's hooks won't work. Even worse, git branchless init doesn't report any error and the aliases still work, meaning you could easily lose a commit if you try to use detached head.

### Version of `git-branchless`

git-branchless-opts 0.7.0-pre.1

### Version of `git`

git version 2.39.0

**Comment by slymon99** [comment]
The temporary fix is to put the hooks path in ~/.gitconfig, run git branchless init, then delete the hooks path from ~/.gitconfig.

**Comment by arxanas** [comment]
@slymon99 can you let me know if https://github.com/arxanas/git-branchless/pull/723 detects your situation? See https://github.com/arxanas/git-branchless/wiki/Runbook#manual-testing for installation instructions.

**Comment by slymon99** [comment]
yup this fixes it
