### ISSUE TITLE
Deleting a branch does not remove the associated `[branch "..."]` section from .git/config

### ISSUE THREAD

**Issue by mlcui-google** [arxanas/git-branchless#728]
### Description of the bug

I took a quick look at my .git/config and saw that there were a few `[branch "..."]` sections from branches that were deleted from a `git sync`. It seems like `hook-detect-empty-commit` isn't deleting these config sections as a `git branch -d` would.

This is a very minor bug - the only issues that occurs with this are:

- a `.git/config` file which gets larger over time, and
- creating a new branch with the same name as a previously git-branchless-deleted branch inherits the settings (remote, upstream, and more) of the old deleted branch.

This is probably an upstream libgit2 issue - see https://github.com/libgit2/libgit2/issues/4582 for a very similar issue - but unlike https://github.com/arxanas/git-branchless/discussions/678 it seems like it could possibly be fixed from git-branchless.

Let me know if you want a concrete reproduction of this.

### Expected behavior

Deleted branches have their `[branch "..."]` section in .git/config deleted.

### Actual behavior

Deleted branches do not have their `[branch "..."]` section in .git/config deleted.

### Version of `git-branchless`

2f0d57e

### Version of `git`

git version 2.39.0.314.g84b9a713c41-goog

**Comment by arxanas** [comment]
Hi @mlcui-google, thanks for reporting. I've also noticed this (and been annoyed by it), but I figured I was misusing Git somehow — good to know that it's actually a bug.
