### ISSUE TITLE
No obvious way to generate man pages

### ISSUE THREAD

**Issue by alerque** [arxanas/git-branchless#828]
### Description

I've been packaging `git-branchless` in the Arch Linux AUR (user repository) for a while now and am considering migrating it to official package repositories. I just bumped the packaging to the new v0.7.0 release, but I'm having trouble figuring out where the rumored man pages are.

I see from #112 the discussion about the topic, but no conclusion. It kind of punts to "disto packager support", but I *am* the distro packager and our tooling does support it, I just can't figure out where to get them *from*. I see in #114 some tooling was added suggesting man pages might be generated by `build.rs` and stuffed in the output dir, but I don't see them there either. In more current code I see a function being run as part of `git branchless init` that suggests it might be stuffing man pages locale to a repository, but I tried that too and didn't find any.

What is the status of having man pages and where can I get them from to add to our packaging?

**Comment by arxanas** [comment]
Hi @alerque, the existing code for `git-branchless init` *would* install man-pages, except that it requires the `man-pages` feature to be enabled, and also the `man-pages` feature was removed at some point in the past. I opened https://github.com/arxanas/git-branchless/pull/830 to create an explicit `git-branchless install-man-pages` command; let me know if that works for you and I can merge it.

**Comment by alerque** [comment]
Thanks for looking into this! I dropped some comments on the PR.
