### ISSUE TITLE
Ignored branches

### ISSUE THREAD

**Issue by edef1c** [arxanas/git-branchless#839]
### Description of the bug

git-annex keeps a branch named git-annex, which is not really meant to be a user-visible detail. It pollutes the smartlog view. I don't see a way of hiding it from git-branchless.

### Expected behavior

Be shown the smartlog for user-controlled branches that contain actual code.

### Actual behavior

A lot of useless commits show up in my smartlog.

**Comment by arxanas** [comment]
Hi @edef1c, you can now use the [`branchless.smartlog.defaultRevset` configuration option](https://github.com/arxanas/git-branchless/wiki/Configuration#branchlesssmartlogdefaultrevset) to specify the default revset to display. You can also pass an argument to `git smartlog` to specify which commits should be displayed (and perhaps make an additional alias for that command).
