### ISSUE TITLE
v0.7.0 fails to build on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [arxanas/git-branchless#842]
### Description of the bug

Hi,

I was trying to update the NetBSD package from 0.6.0 to 0.7.0 but the build fails.
The reason is the new dependency on `ioctl-rs` and a pending PR to add support for NetBSD https://github.com/dcuddeback/ioctl-rs/pull/5, which was never merged.

I can try to patch the crate locally but, why is this needed? `ioctl-rs` hasn't seen a single commit in 5 years and looks to be dead.

Regards

### Expected behavior

0.7.0 builds.

### Actual behavior

0.7.0 fails to build.

### Version of `rustc`

1.67.1

**Comment by arxanas** [comment]
Hi @0323pin, the `ioctl-rs` dependency is a transitive dependency of `portable-pty`, which we use to simulate the PTY for testing. I tried to extract the testing code into a new crate here https://github.com/arxanas/git-branchless/pull/844; can you let me know if that works for you?

**Comment by 0323pin** [comment]
@arxanas thank you!
I'll test building from #844 asap. On my way to work right now but, will report back later today on the results 👍

**Comment by 0323pin** [comment]
@arxanas This fixes the build, thank you.

Let me know if I should push a build of 0.7.0 pulling from this tag into our repositories or, if you want to release something like 0.7.1 before.

Will wait your preference.

**Comment by arxanas** [comment]
@0323pin I pushed [tag v0.7.1](https://github.com/arxanas/git-branchless/releases/tag/v0.7.1). Let me know whether it still builds for you, since I cherry-picked commits into v0.7.0. If so, you can publish for NetBSD and I'll also create an official GitHub release.

**Comment by 0323pin** [comment]
@arxanas Yes, it builds just fine, thanks.
I'll wait until a formal release is out, so I don't get checksum mismatches.

Regards and thank you.

**Comment by 0323pin** [comment]
@arxanas Any news on the release of 0.7.1?
We are heading into a commit freeze ahead of branching the next stable packages iteration. I would like to get this in before the branching.

Thank you,

**Comment by arxanas** [comment]
@0323pin I released https://github.com/arxanas/git-branchless/releases/tag/v0.7.1. Thanks for your help in verifying it.

There is a tiny change to v0.7.1 since you last checked: before, I had accidentally changed the `v0.7.0` heading to `v0.7.1`, but I undid that change and force-pushed the tag. (Shouldn't be important for building.)
