### ISSUE TITLE
`git amend` changes date of commit

### ISSUE THREAD

**Issue by trygvis** [arxanas/git-branchless#852]
### Description of the bug

If I do:

* git prev
* (some fixes)
* git add -u
* git amend

The fix is included and the child commits are rebased on top of the new commit which is great. However, the amended commit how has the current time as its date instead of the original.

### Expected behavior

I would expect the commit's date to be the same as if I had used `git commit --amend` to fix it manually.

### Version of `rustc`

1.63.0

### Automated bug report

I can upload this if necessary.

### Version of `git-branchless`

git-branchless 0.6.0

### Version of `git`

git version 2.39.2

**Comment by arxanas** [comment]
Hi @trygvis,

- Are you referring to the author date or the committer date?
- You can try this configuration setting to inhibit timestamp behavior: https://github.com/arxanas/git-branchless/wiki/Configuration#branchlessrestackpreservetimestamps

**Comment by trygvis** [comment]
Hi @arxanas 

I'm referring to the author date. I was a bit surprised that the end result was a bit different from a normal git commit --amend?. Am I misunderstanding something or is there a reason for it being different from an amended commit?

Anyway, thanks for a superb tool!

**Comment by arxanas** [comment]
@trygvis The rationale is that, in git-branchless, amends are more likely to be substantive changes, so preserving the "author" date is semantically incorrect. On the other hand, rebases via `git move` or `git sync` are typically not meant to change the logical contents of the commit, or changing the commit message with `git reword`, so they shouldn't adjust the author date.
