### ISSUE TITLE
Rename `git undo`?

### ISSUE THREAD

**Issue by arxanas** [arxanas/git-branchless#9]
I think it would be best to rename `git undo`:

* It cannot undo everything. In particular, it can't undo staged or unstaged changes. It's probably best not to market it as undoing "everything".
* There are other `git undo` commands on the market, which do different things. In particular, some of them *can* deal with staged/unstaged changes.
* It's also generally useful to use the `undo` command to view previous states of the repository. You can manually restore a development tree by taking the commit hash and running `git unhide` on it. In fact, that may be a useful command to include into `git undo`, such that it would no longer be a single-purpose command.

Here are some alternative names:

* `git history`:
  * This would probably be hard to search for.
  * `history` is not a verb, but most `git` commands are verbs.
* `git time-travel`:
  * Very cool and good for marketing.
  * May not be intuitive for non-native English speakers?
  * Might be hard to remember if there's a dash or not? But `git` should suggest the correct version automatically.
  * Slightly long. May not be a problem? We could also alias `git tt` to `git time-travel`.
* `git rewind`:
  * Not as cool as `git time-travel`.
  * Probably good for non-native English speakers.
  * Slightly annoying that it's another term in a series of "re-" commands: `git rebase`, `git reset`, `git restore`, `git revert`, `git restack`, `git rerere`.
  * Unclear if this implies that you have to take an action, rather than simply browsing?

**Comment by arxanas** [comment]
@dfabulich I am working on adjusting the README and demos based on our discussion in #6. I would like to make this rename before doing so, since it's one of the main features of `git-branchless`. Do you have any thoughts or a preference for which name to use? I'm leaning towards `git time-travel`.

**Comment by dfabulich** [comment]
For myself, if I saw `git time-travel` I'd have said "eh, what's the point? I already know how to read the git log and check out old revisions; isn't that time travel?"

"Undo" sounds useful, even/especially when I already know how to check out old revisions, because it indicates that I'll be able to run just one easy "undo" command and it'll "just work." The time travel I know how to do by hand requires several commands to dig up the commit I want and go back to it without losing previous work.

Now, you raise a good point that your `git undo` today won't undo stage/unstage, so it kinda won't "just work." But the moral I draw from this is that what the world needs (what the world thinks it needs) is a `git undo` that undoes anything/everything, including staging.

**Comment by arxanas** [comment]
I want to make a `git stage` command anyways, since I don't think the command-line interface for `git add -p` is very good, and there is no simple interface for splitting a commit. I suppose it would be possible to automatically commit the staged changes into a hidden "staged" commit, which would be possible to use later in `git undo`. That might be an acceptable half-way point to "undo anything".

A lot of workflows could be improved by adding custom commands with better UX. Currently, `git rebase` is useful for moving stacks of commits, but not trees. I would like to make a `git move` command to handle the tree case better. As a nice consequence, the `git undo` for `git move` would get a lot better too: currently, `git rebase` emits a bunch of unrelated (from the perspective of `git branchless`) events, so you have to wade through several logically-but-not-technically-grouped entries in `git undo`.

I suppose for now I'll keep it named as `git undo`.

For my future reference, here's are some notes on why `git undo` doesn't work with staged changes:

* If I understand correctly, solutions like https://github.com/nvbn/thefuck and https://github.com/mapmeld/gitjk work by scraping your shell's history. This requires some set up ahead of time (like installing an alias for `git` to intercept commands).
  * Maybe this is acceptable, given that you have to run `git branchless init` in your repository anyways? But I feel like running a command in your Git repository is a lot easier and more reliable than mucking with your shell configuration.
  * Personally, I hate having to add stuff to my `.bashrc`, etc. It's always complicated and doesn't transfer between computers well.
  * If we did require shell setup, it would also mean that we can wrap commands like `git rebase` in a transaction, which would group them together in the `git undo` view.
* `git add`/the act of staging has no hook that we can use.
* Staging changes doesn't move any references, which could be caught with the `reference-transaction` hook.
* The index itself has no reflog or similar, which would allow us to view past versions of the index. It's particularly frustrating since changes which have been staged are [probably in the object database somewhere](https://stackoverflow.com/questions/11094968/in-git-how-can-i-recover-a-staged-file-that-was-reverted-prior-to-committing).
