### ISSUE TITLE
Operations randomly hang and consume tons of memory

### ISSUE THREAD

**Issue by williewillus** [arxanas/git-branchless#938]
### Description of the bug

Operations such as `git prev` or `git checkout --detach` hang and consume tons of memory (>10G).

If I SIGINT the process and check git status, it appears the operation went through.

### Expected behavior

Not hang

### Actual behavior

Hang

### Version of `rustc`

1.65

### Automated bug report

[report.txt](https://github.com/arxanas/git-branchless/files/11513570/report.txt)

**Comment by williewillus** [comment]
Probably related to #937.
I tried uninstalling branchless and reinstalling it into the repo but the problem still persists.

**Comment by williewillus** [comment]
The process hanging has command line `git-branchless hook reference-transaction committed`

**Comment by arxanas** [comment]
Hi @williewillus, do you notice git-branchless printing a lot of output lines saying that it processed new references/branches? You can also try applying https://github.com/arxanas/git-branchless/pull/913 to see if it improves the behavior of the reference-transaction hook.

Can you also say how big your packed-refs file is, i.e. `wc -l .git/packed-refs`?

If you are working with a large repository, the problem might not be with the reference transactions, but instead with working copy snapshots. You can try disabling [`branchless.undo.createSnapshots`](https://github.com/arxanas/git-branchless/wiki/Configuration#branchlessundocreatesnapshots) and see if it helps.

**Comment by surajrmal** [comment]
re-installing git branchless via cargo fixed my issue.

**Comment by arxanas** [comment]
@williewillus does `git smartlog` complete in a reasonable amount of time? It might just be the post-operation smartlog printing which is using too much time and memory, as it's not efficiently implemented (see https://github.com/arxanas/git-branchless/issues/937).

**Comment by williewillus** [comment]
Waleed Khan ***@***.***> writes:

> @williewillus does `git smartlog` complete in a reasonable amount of time? It might just
> be the post-operation smartlog printing which is using too much time and memory, as it's
> not efficiently implemented (see https://github.com/arxanas/git-branchless/issues/937).

git sl completes reasonably quickly, it's just when committing,
amending, or otherwise manipulating the commit graph in my experience.

Would it help for me to zip up my entire repo and send it? It's about 200MiB.

**Comment by arxanas** [comment]
@williewillus unfortunately, I don't have time lately to debug git-branchless issues. If you want to investigate yourself, you can follow the profiling section of the runbook: https://github.com/arxanas/git-branchless/wiki/Runbook#profiling and see what operation is taking too long.

**Comment by eugeneoden** [comment]
Is it possible this is an issue in v0.7.0 (the latest released to crates.io and installed via `cargo install`) which was later fixed?

I ran into this today with v0.7.0 but installing from the repo master (6dcdd06) works fine.

**Comment by arxanas** [comment]
@williewillus want to try building from source as per the above comment? You can see the installation instructions here: https://github.com/arxanas/git-branchless/wiki/Runbook#global-installation

**Comment by williewillus** [comment]
Waleed Khan ***@***.***> writes:

> @williewillus want to try building from source as per the above comment? You can see the
> installation instructions here:
> https://github.com/arxanas/git-branchless/wiki/Runbook#global-installation

I reinstalled from source and it seems to have gone away. I'm guessing
some change since 0.7.1 has fixed it. Maybe a new release is in order?

**Comment by edwintorok** [comment]
Just to add another datapoint: git-branchless 0.7.0 ends up consuming >20G of memory and eventually have to kill it when it doesn't finish 30m later on a repo of mine, but completes successfully once installing the latest git.

**Comment by arxanas** [comment]
@edwintorok what versions of Git were you running before and after?

**Comment by edwintorok** [comment]
@arxanas sorry I should've been clearer by 'the latest git' I meant 'the latest version of git-branchless from git'.
The version of `git` (the tool) is unchanged: 2.41.0, I've changed the version of `git-branchless` from 0.7.0 to latest git-branchless `https://github.com/arxanas/git-branchless#2bf7e754`
